### ISSUE TITLE
QR generate terlalu cepat & qr jadi kecil

### ISSUE THREAD

**Issue by jeffryafandi** [BochilGaming/games-wabot#115]
Halo kak, saya tiba² mendapatkan masalah dalam QR-Gen. dimana qr menjadi sangat cepat refresh nya sekitar 3-5 detik dari 20detik
QR juga menjadi lebih kecil dari biasanya.

Tolong sarannya untuk memperbaiki masalah ini. saya sudah mencoba `--big-qr` tetapi tetap saja tidak bisa.

Sekian, untuk perhatiannya saya sampaikan Terimakasih

**Comment by BochilGaming** [comment]
ccc4ab9
