### ISSUE TITLE
Link Group Wa

### ISSUE THREAD

**Issue by MAYKELL07** [BochilGaming/games-wabot#128]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BochilGaming** [comment]
??

**Comment by BochilGaming** [comment]
> link group wa? link yang di github readme sudah di reset

https://chat.whatsapp.com/BVmECclaym2KcMv9DTDmMa
