### ISSUE TITLE
Gw gak bsa deploy bang eror mulu

### ISSUE THREAD

**Issue by NajwanZaky** [BochilGaming/games-wabot#139]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BochilGaming** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

error nya mana?

**Comment by NajwanZaky** [comment]
> > **Describe the bug** A clear and concise description of what the bug is.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Screenshots** If applicable, add screenshots to help explain your problem.
> > **Desktop (please complete the following information):**
> > 
> > * OS: [e.g. iOS]
> > * Browser [e.g. chrome, safari]
> > * Version [e.g. 22]
> > 
> > **Smartphone (please complete the following information):**
> > 
> > * Device: [e.g. iPhone6]
> > * OS: [e.g. iOS8.1]
> > * Browser [e.g. stock browser, safari]
> > * Version [e.g. 22]
> > 
> > **Additional context** Add any other context about the problem here.
> 
> error nya mana?

Pas npm start gan udh npm install/update msh gtu

**Comment by BochilGaming** [comment]
> > > **Describe the bug** A clear and concise description of what the bug is.
> > > **To Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. Go to '...'
> > > 2. Click on '....'
> > > 3. Scroll down to '....'
> > > 4. See error
> > > 
> > > **Expected behavior** A clear and concise description of what you expected to happen.
> > > **Screenshots** If applicable, add screenshots to help explain your problem.
> > > **Desktop (please complete the following information):**
> > > 
> > > * OS: [e.g. iOS]
> > > * Browser [e.g. chrome, safari]
> > > * Version [e.g. 22]
> > > 
> > > **Smartphone (please complete the following information):**
> > > 
> > > * Device: [e.g. iPhone6]
> > > * OS: [e.g. iOS8.1]
> > > * Browser [e.g. stock browser, safari]
> > > * Version [e.g. 22]
> > > 
> > > **Additional context** Add any other context about the problem here.
> > 
> > 
> > error nya mana?
> 
> Pas npm start gan udh npm install/update msh gtu

Ada ss error nya?

**Comment by NajwanZaky** [comment]
> > > > **Jelaskan bug Deskripsi yang** jelas dan ringkas tentang apa itu bug. 
> > > > **Untuk Mereproduksi** Langkah-langkah untuk mereproduksi perilaku:
> > > > 
> > > > 1. Pergi ke '...'
> > > > 2. Klik '....'
> > > > 3. Gulir ke bawah ke '....'
> > > > 4. Lihat kesalahan
> > > > 
> > > > **Perilaku yang diharapkan** Uraian yang jelas dan ringkas tentang apa yang Anda harapkan terjadi. 
> > > > **Tangkapan layar** Jika ada, tambahkan tangkapan layar untuk membantu menjelaskan masalah Anda. 
> > > > **Desktop (harap lengkapi informasi berikut):**
> > > > 
> > > > * OS: [misalnya iOS]
> > > > * Peramban [misalnya chrome, safari]
> > > > * Versi [misalnya 22]
> > > > 
> > > > **Ponsel Cerdas (harap lengkapi informasi berikut):**
> > > > 
> > > > * Perangkat: [misalnya iPhone6]
> > > > * OS: [misalnya iOS8.1]
> > > > * Browser [misalnya browser stok, safari]
> > > > * Versi [misalnya 22]
> > > > 
> > > > **Konteks tambahan** Tambahkan **konteks** lain tentang masalah di sini.
> > > 
> > > 
> > > errornya mana?
> > 
> > 
> > Pas npm start gan udh npm install/update msh gtu
> 
> Ada ss error nya?

Ada ssnya

**Comment by BochilGaming** [comment]
> > > > > **Jelaskan bug Deskripsi yang** jelas dan ringkas tentang apa itu bug.
> > > > > **Untuk Mereproduksi** Langkah-langkah untuk mereproduksi perilaku:
> > > > > 
> > > > > 1. Pergi ke '...'
> > > > > 2. Klik '....'
> > > > > 3. Gulir ke bawah ke '....'
> > > > > 4. Lihat kesalahan
> > > > > 
> > > > > **Perilaku yang diharapkan** Uraian yang jelas dan ringkas tentang apa yang Anda harapkan terjadi.
> > > > > **Tangkapan layar** Jika ada, tambahkan tangkapan layar untuk membantu menjelaskan masalah Anda.
> > > > > **Desktop (harap lengkapi informasi berikut):**
> > > > > 
> > > > > * OS: [misalnya iOS]
> > > > > * Peramban [misalnya chrome, safari]
> > > > > * Versi [misalnya 22]
> > > > > 
> > > > > **Ponsel Cerdas (harap lengkapi informasi berikut):**
> > > > > 
> > > > > * Perangkat: [misalnya iPhone6]
> > > > > * OS: [misalnya iOS8.1]
> > > > > * Browser [misalnya browser stok, safari]
> > > > > * Versi [misalnya 22]
> > > > > 
> > > > > **Konteks tambahan** Tambahkan **konteks** lain tentang masalah di sini.
> > > > 
> > > > 
> > > > errornya mana?
> > > 
> > > 
> > > Pas npm start gan udh npm install/update msh gtu
> > 
> > 
> > Ada ss error nya?
> 
> Ada ssnya

iy mana?

**Comment by NajwanZaky** [comment]
> **Jelaskan bug Deskripsi yang** jelas dan ringkas tentang apa itu bug.
> 
> **Untuk Mereproduksi** Langkah-langkah untuk mereproduksi perilaku:
> 
> 1. Pergi ke '...'
> 2. Klik '....'
> 3. Gulir ke bawah ke '....'
> 4. Lihat kesalahan
> 
> **Perilaku yang diharapkan** Uraian yang jelas dan ringkas tentang apa yang Anda harapkan terjadi.
> 
> **Tangkapan layar** Jika ada, tambahkan tangkapan layar untuk membantu menjelaskan masalah Anda.
> 
> **Desktop (harap lengkapi informasi berikut):**
> 
> * OS: [misalnya iOS]
> * Peramban [misalnya chrome, safari]
> * Versi [misalnya 22]
> 
> **Ponsel Cerdas (harap lengkapi informasi berikut):**
> 
> * Perangkat: [misalnya iPhone6]
> * OS: [misalnya iOS8.1]
> * Browser [misalnya browser stok, safari]
> * Versi [misalnya 22]
> 
> **Konteks tambahan** Tambahkan **konteks** lain tentang masalah di sini.



> > > > > > **Jelaskan bug Deskripsi yang** jelas dan ringkas tentang apa itu bug. 
> > > > > > **Untuk Mereproduksi** Langkah-langkah untuk mereproduksi perilaku:
> > > > > > 
> > > > > > 1. Pergi ke '...'
> > > > > > 2. Klik '....'
> > > > > > 3. Gulir ke bawah ke '....'
> > > > > > 4. Lihat kesalahan
> > > > > > 
> > > > > > **Perilaku yang diharapkan** Uraian yang jelas dan ringkas tentang apa yang Anda harapkan terjadi. 
> > > > > > **Tangkapan layar** Jika ada, tambahkan tangkapan layar untuk membantu menjelaskan masalah Anda. 
> > > > > > **Desktop (harap lengkapi informasi berikut):**
> > > > > > 
> > > > > > * OS: [misalnya iOS]
> > > > > > * Peramban [misalnya chrome, safari]
> > > > > > * Versi [misalnya 22]
> > > > > > 
> > > > > > **Ponsel Cerdas (harap lengkapi informasi berikut):**
> > > > > > 
> > > > > > * Perangkat: [misalnya iPhone6]
> > > > > > * OS: [misalnya iOS8.1]
> > > > > > * Browser [misalnya stok browser, safari]
> > > > > > * Versi [misalnya 22]
> > > > > > 
> > > > > > **Konteks Tambahan** Jumlah Harga: Tambahkan **Konteks** Lain TENTANG masalah here.
> > > > > 
> > > > > 
> > > > > errornya mana?
> > > > 
> > > > 
> > > > Pas npm start gan udh npm install/update msh gtu
> > > 
> > > 
> > > Ada ss error nya?
> > 
> > 
> > Ada ssnya
> 
> iy mana?

![Uploading Screenshot_2021-11-25-05-41-14-094_com.termux.jpg…]()

**Comment by BochilGaming** [comment]
gk bisa diliat

**Comment by NajwanZaky** [comment]
Send Name IG Atau Wa Aja Deh

**Comment by BochilGaming** [comment]
https://chat.whatsapp.com/BVmECclaym2KcMv9DTDmMa

**Comment by NajwanZaky** [comment]
Wa lu yg mana

**Comment by unx21** [comment]
Di send link group biar banyak yang bisa bantu jawab :v

**Comment by NajwanZaky** [comment]
> Di send link group biar banyak yang bisa bantu jawab :v

Malu gw ngomong nya wkwk

**Comment by BochilGaming** [comment]
> > Di send link group biar banyak yang bisa bantu jawab :v
> 
> Malu gw ngomong nya wkwk

Tanyain aja :v

**Comment by BochilGaming** [comment]
> Di send link group biar banyak yang bisa bantu jawab :v

Wkwkkw

**Comment by unx21** [comment]
> > Di send link group biar banyak yang bisa bantu jawab :v
> 
> Malu gw ngomong nya wkwk

Duhh, parah sih
Di grup paling 100 orang yang liat, sedangkan disini bisa lebih dari 1000 orang :v
