### ISSUE TITLE
error scanqr code in heroku

### ISSUE THREAD

**Issue by XstepAhead** [BochilGaming/games-wabot#143]
WARN [2021-12-01 13:05:56.661 +0000] (17): connect attempt 2 failed: Error: bad rs block @ typeNumber:1/errorCorrectLevel:undefined, retrying...
2021-12-01T13:05:56.661592+00:00 app[web.1]: class: "Baileys"
2021-12-01T13:05:56.661593+00:00 app[web.1]: error: {}

**Comment by unx21** [comment]
> WARN [2021-12-01 13:05:56.661 +0000] (17): connect attempt 2 failed: Error: bad rs block @ typeNumber:1/errorCorrectLevel:undefined, retrying... 2021-12-01T13:05:56.661592+00:00 app[web.1]: class: "Baileys" 2021-12-01T13:05:56.661593+00:00 app[web.1]: error: {}

Upload your session first

**Comment by XstepAhead** [comment]
> > WARN [2021-12-01 13:05:56.661 +0000] (17): connect attempt 2 failed: Error: bad rs block @ typeNumber:1/errorCorrectLevel:undefined, retrying... 2021-12-01T13:05:56.661592+00:00 app[web.1]: class: "Baileys" 2021-12-01T13:05:56.661593+00:00 app[web.1]: error: {}
> 
> Upload your session first

where

**Comment by ZTRdiamond** [comment]
Where to put the session?

**Comment by BochilGaming** [comment]
> Where to put the session?

Fork this repo, and scan in your local (termux, pc) and aploud to your fork repo,  and deploy your fork repo to heroku

**Comment by Bintangp02** [comment]
> WARN [2021-12-01 13:05:56.661 +0000] (17): connect attempt 2 failed: Error: bad rs block @ typeNumber:1/errorCorrectLevel:undefined, retrying... 2021-12-01T13:05:56.661592+00:00 app[web.1]: class: "Baileys" 2021-12-01T13:05:56.661593+00:00 app[web.1]: error: {}

Before you run to heroku, first you have to run Termux or PC after that take the session.json data and move it to a funny disk or in the Sdcard Then upload to github and log back in and deploy according to the existing steps...

**Comment by XstepAhead** [comment]
OKEY MAKASIHH :V
