### ISSUE TITLE
Please add features, specific responses

### ISSUE THREAD

**Issue by Bintangp02** [BochilGaming/games-wabot#149]
Eng: Please Add a feature that only responds to my bot menu like in plugin.js menu outside of that there is no response, and this also reduces garbage or unimportant responses entering the terminal 

ind: Tolong Tambahkan fitur yang hanya merespon menu bot saya seperti di menu plugin.js di luar itu tidak ada respons, dan ini juga mengurangi sampah atau respons tidak penting yang masuk ke terminal 

Trimakasih Kepada Developer

**Comment by unx21** [comment]
Kan kalo gaada di plugins emang gabakal respon bot nya. Tolong jelaskan lebih rinci tentang fitur yang anda inginkan

**Comment by BochilGaming** [comment]
> Eng: Please Add a feature that only responds to my bot menu like in plugin.js menu outside of that there is no response, and this also reduces garbage or unimportant responses entering the terminal
> 
> ind: Tolong Tambahkan fitur yang hanya merespon menu bot saya seperti di menu plugin.js di luar itu tidak ada respons, dan ini juga mengurangi sampah atau respons tidak penting yang masuk ke terminal
> 
> Trimakasih Kepada Developer

you can delete the plugins you don't want

**Comment by Bintangp02** [comment]
> Kan kalo gaada di plugins emang gabakal respon bot nya. Tolong jelaskan lebih rinci tentang fitur yang anda inginkan


Eng : I mean only received messages are in the plugin that goes in terminal / termux 

Ind : Maksud saya hanya pesan yang diterima yang  di plugin yang masuk ke terminal/termux

Pesan pesan lain seperti contoh P, oke , selamat pagi dll (semua) di luar dari respon plugin pesan tersebut tidak akan masuk ke terminal

**Comment by BochilGaming** [comment]
> > Kan kalo gaada di plugins emang gabakal respon bot nya. Tolong jelaskan lebih rinci tentang fitur yang anda inginkan
> 
> Eng : I mean only received messages are in the plugin that goes in terminal / termux
> 
> Ind : Maksud saya hanya pesan yang diterima yang di plugin yang masuk ke terminal/termux
> 
> Pesan pesan lain seperti contoh P, oke , selamat pagi dll (semua) di luar dari respon plugin pesan tersebut tidak akan masuk ke terminal

https://github.com/BochilGaming/games-wabot/blob/f265ff34bbc2b4c88729c4665c6d5bbcd109dfa6/handler.js#L433
change to 
```js
if (m.isCommand) require('./lib/print')(m, this) 
```

**Comment by Bintangp02** [comment]
> > > Kan kalo gaada di plugins emang gabakal respon bot nya. Tolong jelaskan lebih rinci tentang fitur yang anda inginkan
> > 
> > 
> > Eng : I mean only received messages are in the plugin that goes in terminal / termux
> > Ind : Maksud saya hanya pesan yang diterima yang di plugin yang masuk ke terminal/termux
> > Pesan pesan lain seperti contoh P, oke , selamat pagi dll (semua) di luar dari respon plugin pesan tersebut tidak akan masuk ke terminal
> 
> https://github.com/BochilGaming/games-wabot/blob/f265ff34bbc2b4c88729c4665c6d5bbcd109dfa6/handler.js#L433
> 
> 
> change to
> ```js
> if (m.isCommand) require('./lib/print')(m, this) 
> ```

Trimakasih telah membantu.!
