### ISSUE TITLE
Cari polosan MD

### ISSUE THREAD

**Issue by botstylee** [BochilGaming/games-wabot#161]
Coy ada gak gitu SC polosan MD yang handler tepatnya base nuru yg udah MD soal buat gw kembangin yang polos banget pokoknya

**Comment by botstylee** [comment]
Nyari yg polos bukan yg full fitur

**Comment by BochilGaming** [comment]
> Nyari yg polos bukan yg full fitur

Di branch md plugins nya hapus semua aja, kan jadi polosan :v

**Comment by scoder37** [comment]
@BochilGaming nah :v

**Comment by unknowkzr** [comment]
> Coy ada gak gitu SC polosan MD yang handler tepatnya base nuru yg udah MD soal buat gw kembangin yang polos banget pokoknya


https://github.com/adulalhy/Nana-MD

> Coy ada gak gitu SC polosan MD yang handler tepatnya base nuru yg udah MD soal buat gw kembangin yang polos banget pokoknya

setau gw sih ini
https://github.com/adulalhy/Nana-MD
https://github.com/ilmanhdyt/ShiraoriBot-Md

itu plugins handler
