### ISSUE TITLE
menunggu update base

### ISSUE THREAD

**Issue by scoder37** [BochilGaming/games-wabot#162]

**Comment by BochilGaming** [comment]
> _No description provided._

:v

**Comment by botstylee** [comment]
> > _No description provided._
> 
> :v

Menunggu tuh dia seperti dia menunggu seseorang yang belum tentu pasti :v

**Comment by BochilGaming** [comment]
> > > _No description provided._
> > 
> > 
> > :v
> 
> Menunggu tuh dia seperti dia menunggu seseorang yang belum tentu pasti :v

okwokw
