### ISSUE TITLE
Request fitur game werewolf bang 

### ISSUE THREAD

**Issue by pa7rickr** [BochilGaming/games-wabot#164]
Bikin fitur game werewolf bang hehe

**Comment by BochilGaming** [comment]
> Bikin fitur game werewolf bang hehe

Pull req bang kalau bisa buat :)

**Comment by PatrickStar720** [comment]
> > Bikin fitur game werewolf bang hehe
> 
> Pull req bang kalau bisa buat :)

ok bang
