### ISSUE TITLE
[BUG] send audio/video in YT

### ISSUE THREAD

**Issue by Jarvis2301** [BochilGaming/games-wabot#182]
![Screenshot_20220119-122949](https://user-images.githubusercontent.com/88648954/150064474-eb51f879-ee04-4a28-b6e3-26f854c20a49.png)

**Comment by unx21** [comment]
Maksudnya gimana bang?

**Comment by Jarvis2301** [comment]
> Maksudnya gimana bang?

Tampilin File audionya

**Comment by BochilGaming** [comment]
> > Maksudnya gimana bang?
> 
> Tampilin File audionya

harus nya sih tampil kalau normal, coba cek di terminal apakah ada error?

**Comment by unx21** [comment]
> > Maksudnya gimana bang?
> 
> Tampilin File audionya

Ooo

**Comment by BochilGaming** [comment]
close karena gk ada respon dari yang buat issue

**Comment by unx21** [comment]
> close karena gk ada respon dari yang buat issue

![Screenshot_20220126-140615_Termux](https://user-images.githubusercontent.com/84166927/151125040-63124241-8816-4ddc-bb7d-939493576f7a.png)
Punya saya kek gini bang :)
