### ISSUE TITLE
Request runtime bio dan custom thumb menu

### ISSUE THREAD

**Issue by Klpinhub** [BochilGaming/games-wabot#188]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Klpinhub** [comment]
Y

**Comment by Klpinhub** [comment]
Y

**Comment by unx21** [comment]
Ada masalah apa sih bro

**Comment by BochilGaming** [comment]
wkwkw, pull req aja kalau bisa buat nanti ku merge :v

**Comment by unx21** [comment]
> wkwkw, pull req aja kalau bisa buat nanti ku merge :v

Nanti pull req nya di open close kek ni issue wkwkwk

**Comment by BochilGaming** [comment]
> > wkwkw, pull req aja kalau bisa buat nanti ku merge :v
> 
> Nanti pull req nya di open close kek ni issue wkwkwk

lmao :v

**Comment by botstylee** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Mau di buat bruh tapi sayangnya gw mager banget lagi nyaman di zona nyantai nge-push ml

**Comment by BochilGaming** [comment]
> > **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > **Describe the solution you'd like** A clear and concise description of what you want to happen.
> > **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> > **Additional context** Add any other context or screenshots about the feature request here.
> 
> Mau di buat bruh tapi sayangnya gw mager banget lagi nyaman di zona nyantai nge-push ml

wkwkw

**Comment by Klpinhub** [comment]
> 



> Ada masalah apa sih bro

Laper belom di suruh makan sama ayang😔

**Comment by unx21** [comment]
> > 
> 
> > Ada masalah apa sih bro
> 
> Laper belom di suruh makan sama ayang😔

Kasihan... jadi budak ayang

**Comment by Klpinhub** [comment]
> > > 
> > 
> > 
> > > Ada masalah apa sih bro
> > 
> > 
> > Laper belom di suruh makan sama ayangpensive
> 
> Kasihan... jadi budak ayang

Kan kamu ayang aku... SLIBAW😔🤟

**Comment by unx21** [comment]
> > > > 
> > > 
> > > 
> > > > Ada masalah apa sih bro
> > > 
> > > 
> > > Laper belom di suruh makan sama ayangpensive
> > 
> > 
> > Kasihan... jadi budak ayang
> 
> Kan kamu ayang aku... SLIBAW😔🤟

Karena gapunya ayang makanya ngaku² jadi ayang orang ✌️
