### ISSUE TITLE
Fiture kick di SC ini bisa gak si ?

### ISSUE THREAD

**Issue by botstylee** [BochilGaming/games-wabot#190]

**Comment by BlueShiYT** [comment]
Bisa, on restrict dulu klo gk salah

**Comment by BochilGaming** [comment]
> Bisa, on restrict dulu klo gk salah

[iy](https://github.com/BochilGaming/games-wabot#--restrict)

**Comment by Klpinhub** [comment]
> 

Tetep ga bisa, hadehh🥴

**Comment by unx21** [comment]
> > 
> 
> Tetep ga bisa, hadehh🥴

Hmm
