### ISSUE TITLE
Bug command link

### ISSUE THREAD

**Issue by BlueShiYT** [BochilGaming/games-wabot#196]
Yg command .link emang nge bug atau gimana? Pas di coba hanya ada kata "Hanya Bisa Buka Di Grup" padahal lagi di group

**Comment by botstylee** [comment]
> Yg command .link emang nge bug atau gimana? Pas di coba hanya ada kata "Hanya Bisa Buka Di Grup" padahal lagi di group

Maksudnya gimana gak paham saya

**Comment by BlueShiYT** [comment]
> > Yg command .link emang nge bug atau gimana? Pas di coba hanya ada kata "Hanya Bisa Buka Di Grup" padahal lagi di group
> 
> Maksudnya gimana gak paham saya

Jadi gini kan ada command .link nah seharusnya ngirim link groupnya, tapi ada kata "hanya bisa di buka di group" tapiii gw make command .link nya di group gw

**Comment by botstylee** [comment]
> > > Yg command .link emang nge bug atau gimana? Pas di coba hanya ada kata "Hanya Bisa Buka Di Grup" padahal lagi di group
> > 
> > 
> > Maksudnya gimana gak paham saya
> 
> Jadi gini kan ada command .link nah seharusnya ngirim link groupnya, tapi ada kata "hanya bisa di buka di group" tapiii gw make command .link nya di group gw

Ok saya cek dulu

**Comment by botstylee** [comment]
![Screenshot_2022-01-29-12-24-43-70_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/85060672/151648450-7b8fa647-3363-4b8a-9a5e-5ba2fbf531d5.png)
Di saya lancar kok

**Comment by botstylee** [comment]
Sudah saya pullreq yang link sudah bisa tinggal di terima acil

**Comment by botstylee** [comment]
Saya lupa itu yg grup ente bikin true aja pantes gak bisa wkwkwkwk
