### ISSUE TITLE
heroku error!!!!

### ISSUE THREAD

**Issue by anshuljai** [BochilGaming/games-wabot#20]
bot database is not saving up in heroku 🙄

**Comment by BochilGaming** [comment]
Hmm....

**Comment by BochilGaming** [comment]
> bot database is not saving up in heroku 🙄

do you have a screenshot of the error?

**Comment by anshuljai** [comment]
its not saving...when i turn off and turn back on...all users regustered gone

**Comment by BochilGaming** [comment]
> its not saving...when i turn off and turn back on...all users regustered gone

is it not now?
