### ISSUE TITLE
HELP [EROR QR TIDAK BISA DI SCAN]

### ISSUE THREAD

**Issue by Bintangp02** [BochilGaming/games-wabot#219]
Saya mengunakan wa biasa belum saya tautkan ke md tapi tidak bisa untuk di scan !
ling untukdi ping yang mana?
```
https://replit.com/@Bintangp02/bintangp
atau
https://bintangp.bintangp02.repl.co
```
![EROR_Bntgp02](https://user-images.githubusercontent.com/80300921/154888345-4ab969f8-ba41-4c08-bff3-730f23955d41.png)
!

**Comment by botstylee** [comment]
> Saya mengunakan wa biasa belum saya tautkan ke md tapi tidak bisa untuk di scan ! ling untukdi ping yang mana?
> 
> ```
> https://replit.com/@Bintangp02/bintangp
> atau
> https://bintangp.bintangp02.repl.co
> ```
> 
> ![EROR_Bntgp02](https://user-images.githubusercontent.com/80300921/154888345-4ab969f8-ba41-4c08-bff3-730f23955d41.png) !

Bukan versi MD di update terbaru lagi ya

**Comment by botstylee** [comment]
npm i -g @adiwajshing/baileys@4.0.0

**Comment by BochilGaming** [comment]
> Saya mengunakan wa biasa belum saya tautkan ke md tapi tidak bisa untuk di scan ! ling untukdi ping yang mana?
> 
> ```
> https://replit.com/@Bintangp02/bintangp
> atau
> https://bintangp.bintangp02.repl.co
> ```
> 
> ![EROR_Bntgp02](https://user-images.githubusercontent.com/80300921/154888345-4ab969f8-ba41-4c08-bff3-730f23955d41.png) !

multi-device (MD)?

**Comment by Bintangp02** [comment]
oke bang nanti kalau eror takopen lagi trimm
