### ISSUE TITLE
Add Feature and Kick Feature 

### ISSUE THREAD

**Issue by Goldn7799** [BochilGaming/games-wabot#221]
**Describe the bug**
add and kick features don't work and some bugs in games like family 100 and other's, baileys error on linux

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04LTS]
 - Browser [e.g. chrome, FireFox]
 - Version [e.g. 20.04LTS]

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi9]
 - OS: [e.g. Android 11]
 - Browser [e.g. chrome, edge]
 - Version [e.g. 11]
.

**Comment by BochilGaming** [comment]
> **Describe the bug** add and kick features don't work and some bugs in games like family 100 and other's, baileys error on linux
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Ubuntu 20.04LTS]
> * Browser [e.g. chrome, FireFox]
> * Version [e.g. 20.04LTS]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Redmi9]
> * OS: [e.g. Android 11]
> * Browser [e.g. chrome, edge]
> * Version [e.g. 11]
>   .

use legacy (branch main) or MD (branch multi-device) ?

**Comment by syeifsultan** [comment]
> 

I use main Branch

**Comment by syeifsultan** [comment]
> > **Describe the bug** add and kick features don't work and some bugs in games like family 100 and other's, baileys error on linux
> > **Desktop (please complete the following information):**
> > 
> > * OS: [e.g. Ubuntu 20.04LTS]
> > * Browser [e.g. chrome, FireFox]
> > * Version [e.g. 20.04LTS]
> > 
> > **Smartphone (please complete the following information):**
> > 
> > * Device: [e.g. Redmi9]
> > * OS: [e.g. Android 11]
> > * Browser [e.g. chrome, edge]
> > * Version [e.g. 11]
> >   .
> 
> use legacy (branch main) or MD (branch multi-device) ?

I use Main Branch

**Comment by Goldn7799** [comment]
> > **Describe the bug** add and kick features don't work and some bugs in games like family 100 and other's, baileys error on linux
> > **Desktop (please complete the following information):**
> > 
> > * OS: [e.g. Ubuntu 20.04LTS]
> > * Browser [e.g. chrome, FireFox]
> > * Version [e.g. 20.04LTS]
> > 
> > **Smartphone (please complete the following information):**
> > 
> > * Device: [e.g. Redmi9]
> > * OS: [e.g. Android 11]
> > * Browser [e.g. chrome, edge]
> > * Version [e.g. 11]
> >   .
> 
> use legacy (branch main) or MD (branch multi-device) ?

I Use main Branch, sorry Salah Akun Reply
