### ISSUE TITLE
Tag dong orangnya

### ISSUE THREAD

**Issue by botstylee** [BochilGaming/games-wabot#222]
![Screenshot_2022-02-22-14-53-58-49_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/85060672/155086063-466faa73-75b1-4218-b20d-e82462ad8ed0.png)
Yhahahah lucu nih orang, nomer bot sapa nih sama sama recode ngebacot doang gede

**Comment by unx21** [comment]
> ![Screenshot_2022-02-22-14-53-58-49_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/85060672/155086063-466faa73-75b1-4218-b20d-e82462ad8ed0.png) Yhahahah lucu nih orang, nomer bot sapa nih sama sama recode ngebacot doang gede

Woow

**Comment by botstylee** [comment]
> > ![Screenshot_2022-02-22-14-53-58-49_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/85060672/155086063-466faa73-75b1-4218-b20d-e82462ad8ed0.png) Yhahahah lucu nih orang, nomer bot sapa nih sama sama recode ngebacot doang gede
> 
> Woow

Sok keras banget orangnya padahal dia sendiri make base orang juga lucu banget

**Comment by unx21** [comment]
Ngerii

**Comment by BochilGaming** [comment]
ngeerii, dibuat issue :v

**Comment by botstylee** [comment]
> ngeerii, dibuat issue :v

Mau nyari github dia yg baru sapa tau ada yg tau

**Comment by Bintangp02** [comment]
> > ngeerii, dibuat issue :v
> 
> Mau nyari github dia yg baru sapa tau ada yg tau

waduh bang ada juga org kek gitu di ngk mikir apa y bacot nak jbeh kwkw
jgn serang gw xixixi
