### ISSUE TITLE
Eror main.js multi-device on linux

### ISSUE THREAD

**Issue by Goldn7799** [BochilGaming/games-wabot#227]
**Describe the bug**
Eror Module baileys in main.js eror useSingleFilesAuthState Not Found On baileys, eror exit code 1.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome, FireFox
- Terminal : Terminalonogy
 - Version : 20.04LTS

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android
 - Browser: Chrome, Edge
 - Version: 11

**Additional context**
Baileys Dont Full Downloaded On Linux

**Comment by BochilGaming** [comment]
can you show me the full log?. i use linux to run the bot but i don't get any error like that

**Comment by Goldn7799** [comment]
> can you show me the full log?. i use linux to run the bot but i don't get any error like that

![Screenshot_2022-02-25-11-35-23-258_com iiordanov bVNC](https://user-images.githubusercontent.com/56997031/155655391-40affde9-4ccd-4cd1-9723-21c343e33799.jpg)
@BochilGaming

**Comment by BochilGaming** [comment]
this [commit](https://github.com/BochilGaming/games-wabot/commit/b1974db32b6811c1bea2e458f3f5c08e7700b59d) fix your issue?

**Comment by Goldn7799** [comment]
> this [commit](https://github.com/BochilGaming/games-wabot/commit/b1974db32b6811c1bea2e458f3f5c08e7700b59d) fix your issue?

All Fixed, Thanks @BochilGaming

**Comment by BochilGaming** [comment]
You're welcome
