### ISSUE TITLE
{SOLVED} [REQUEST] (MD) Delete.js & Button Location image in simple.js!

### ISSUE THREAD

**Issue by DineshValor** [BochilGaming/games-wabot#228]
**Button Location Image Message code line missing in ./lib/simple.js, or am i missed somewhere?**

Image location looks much better, and prevent saving images in gallery.

**Comment by BochilGaming** [comment]
> **Button Location Image Message code line missing in ./lib/simple.js, or am i missed somewhere?**
> 
> Image location looks much better, and prevent saving images in gallery.

```js
conn.sendButton(m.chat, 'hi', global.author, buffer, [['menu', '/menu']], m, { asLocation: true })
```

**Comment by DineshValor** [comment]
If anyone want to use Hydrated Buttons Image Location then below is the example to do that:

Sample-
conn.sendHydrated(m.chat, text.trim(), author, 'link.jpg', 'template-url', 'Template-URL', '0123456789', 'Template-CALL', [
      ['Donate', '/donasi'],
      ['Speed', '/ping'],
      ['Owner', '/owner']
    ], m, {asLocation: true})

Example-
conn.sendHydrated(m.chat, 'one', 'two', 'https://telegra.ph/file/fe5883c8011fd033e395c.jpg', 'https://github.com/BochilGaming/Games-wabot', 'Github', '0123456789', 'Call', [
      ['Donate', '/donasi'],
      ['Speed', '/ping'],
      ['Owner', '/owner']
    ], m, {asLocation: true})
![Screenshot_20220225-135044](https://user-images.githubusercontent.com/98645523/155680569-01c54572-5b44-4a2b-81c2-9935e1519326.jpg)


If didn't want any button or template just replace them by <null> -

For Example-
conn.sendHydrated(m.chat, 'one', 'two', 'https://telegra.ph/file/fe5883c8011fd033e395c.jpg', 'https://github.com/BochilGaming/Games-wabot', 'Github', null, null, [
      ['Speed', '/ping'],
      ['Owner', '/owner']
    ], m, {asLocation: true})
![Screenshot_20220225-134848](https://user-images.githubusercontent.com/98645523/155680184-83980bdf-8d56-4b96-baa8-7a10234b70e6.jpg)

**Comment by BochilGaming** [comment]
can you make pull request to add that code to README.md ?

**Comment by DineshValor** [comment]
> can you make pull request to add that code to README.md ?

Yeah, i will try my best to make these code in README.md
