### ISSUE TITLE
askk

### ISSUE THREAD

**Issue by Natx-C** [BochilGaming/games-wabot#230]
bang ini kenapa ya?, 
![Screenshot_2022-02-25-10-59-51-94](https://user-images.githubusercontent.com/83612604/155651654-34d70faf-ab9e-48bb-b8e5-498697d7e145.jpg)
apa di rename dulu file yg baru di upload, dari .js jd .cjs ?
btw ini yg versi MD

**Comment by BochilGaming** [comment]
> bang ini kenapa ya?, ![Screenshot_2022-02-25-10-59-51-94](https://user-images.githubusercontent.com/83612604/155651654-34d70faf-ab9e-48bb-b8e5-498697d7e145.jpg) apa di rename dulu file yg baru di upload, dari .js jd .cjs ? btw ini yg versi MD

MD pakek ESM, jadi require gk ada, pakek import buat gantinya atau bisa buat require pakek
```js
const require = global.__require(import.meta.url)
const a = require('b') // gk bakal error
```

**Comment by Natx-C** [comment]
> > bang ini kenapa ya?, ![Screenshot_2022-02-25-10-59-51-94](https://user-images.githubusercontent.com/83612604/155651654-34d70faf-ab9e-48bb-b8e5-498697d7e145.jpg) apa di rename dulu file yg baru di upload, dari .js jd .cjs ? btw ini yg versi MD
> 
> MD pakek ESM, jadi require gk ada, pakek import buat gantinya atau bisa buat require pakek
> 
> ```js
> const require = global.__require(import.meta.url)
> const a = require('b') // gk bakal error
> ```

taroh di line brp?

**Comment by BochilGaming** [comment]
> > > bang ini kenapa ya?, ![Screenshot_2022-02-25-10-59-51-94](https://user-images.githubusercontent.com/83612604/155651654-34d70faf-ab9e-48bb-b8e5-498697d7e145.jpg) apa di rename dulu file yg baru di upload, dari .js jd .cjs ? btw ini yg versi MD
> > 
> > 
> > MD pakek ESM, jadi require gk ada, pakek import buat gantinya atau bisa buat require pakek
> > ```js
> > const require = global.__require(import.meta.url)
> > const a = require('b') // gk bakal error
> > ```
> 
> taroh di line brp?

di filemu yang ada require
