### ISSUE TITLE
{Solved} [BIG ISSUE] (MD) /unban chat not working after /chatban done.

### ISSUE THREAD

**Issue by DineshValor** [BochilGaming/games-wabot#233]
**Once /banchat done, then /unbanchat not working at all in that particular group/chat**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any whatsapp group/chat.
2. Type command '/banchat' (now bot Stop reply in that particular group/chat).
3. Now type '/unbanchat' to unban chat for bot in that particular group/chat (but nothing happened).
4. Still Bot is ban, but working in different group/chats.

**Temporary Fix solution*
To fix this issue, need to delete mongodb database or locally database.json file and restart bot.

**Expected behavior**
/unbanchat must be working after /banchat done.

**Screenshots**
![Screenshot_20220225-214219](https://user-images.githubusercontent.com/98645523/155749370-907837cf-782e-4a29-be33-11189dcbebc3.jpg)

**"True" value not change to "false"  by /unbanchat command, that cause bot not working at all**

![Screenshot_20220225-230101](https://user-images.githubusercontent.com/98645523/155761333-ff334eca-b2d4-4478-bf31-3423d05dd9a0.jpg)

**Comment by BochilGaming** [comment]
Does it fix?

**Comment by DineshValor** [comment]
> Does it fix?

Let me try

**Comment by DineshValor** [comment]
> Does it fix?

Got new error in fresh installation (Ubuntu Termux);
![Screenshot_20220226-200515](https://user-images.githubusercontent.com/98645523/155847015-14eb5880-acc5-4ce2-a8bf-be2ce7191551.jpg)

**Comment by DineshValor** [comment]
Checking in progress...

**Comment by DineshValor** [comment]
> Does it fix?

Fixed, Great, very fast resolved.
