### ISSUE TITLE
Multi device 

### ISSUE THREAD

**Issue by ilhamn2405** [BochilGaming/games-wabot#235]
![Screenshot_Termux_20220226-001630](https://user-images.githubusercontent.com/43334234/155759029-916d03d2-1cf0-4d2b-9d7f-dce2b2540584.png)
Mengapa saya sqan menggunakan multi perangkat seperti ini bang?

**Comment by Oktaviola23490** [comment]
Gk tau juga bang :v

Pada tanggal Sab, 26 Feb 2022 00.21, ilhamn2405 ***@***.***>
menulis:

**Comment by DineshValor** [comment]
> 

1. Install Ubuntu in termux
2. Install all necessary buildpacks for Ubuntu
3. Open udroid (Ubuntu) inside termux
4. Clone repo inside Ubuntu
5. Install necessary buildpack for bot like ffmg, etc
6. npm install
7. npm update
8. Now you ready to scan code.
Above all process take around more than 2gb internet and space in your device. Do as per your risk.

**Comment by BochilGaming** [comment]
> ![Screenshot_Termux_20220226-001630](https://user-images.githubusercontent.com/43334234/155759029-916d03d2-1cf0-4d2b-9d7f-dce2b2540584.png) Mengapa saya sqan menggunakan multi perangkat seperti ini bang?

Kalau mau pakke multi-device pakek yang branch MD

**Comment by ilhamn2405** [comment]
> > ![Screenshot_Termux_20220226-001630](https://user-images.githubusercontent.com/43334234/155759029-916d03d2-1cf0-4d2b-9d7f-dce2b2540584.png)Mengapa saya sqan menggunakan multi perangkat seperti ini bang?
> 
> Kalau mau pakke multi-device pakek yang branch MD

Branch md yg mana mas?? Saya masih pemula wkwk

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220226-093828](https://user-images.githubusercontent.com/43334234/155825813-1dd8adcb-5478-4d01-a39d-7b75fa5d007b.png)
npm install branch md, saran bang?

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220226-104926](https://user-images.githubusercontent.com/43334234/155827849-5deaf198-6efe-40b1-bf32-897da81ad098.png)
bash install.sh terus gagal di branch md

**Comment by BochilGaming** [comment]
npm i && node .

**Comment by BochilGaming** [comment]
npm i qrcode-terminal

**Comment by DineshValor** [comment]
> 

What is your termux and android verison ?

**Comment by DineshValor** [comment]
> ![Screenshot_Termux_20220226-104926](https://user-images.githubusercontent.com/43334234/155827849-5deaf198-6efe-40b1-bf32-897da81ad098.png) Udah ganti source ke branch md pas bash install.sh malah gini

Its a termux issue, I'm not sure but you can try below termux-mod (today received recommendation from a friend)
https://www.mediafire.com/file/f01sbphqjsd37b3/TermuxMod.apk/file

**Comment by ilhamn2405** [comment]
> > ![Screenshot_Termux_2220226-104926](https://user-images.githubusercontent.com/43334234/155827849-5deaf198-6efe-40b1-bf32-897da81ad098.png)Udah ganti source ke branch md pas bash install.sh malah gini
> 
> Ini masalah termux, saya tidak yakin tetapi Anda dapat mencoba termux-mod di bawah ini (hari ini menerima rekomendasi dari seorang teman) https://www.mediafire.com/file/f01sbphqjsd37b3/TermuxMod.apk/file
> 
> Dan juga menggunakan `pkg install nodejs-lts`tidak `pkg install nodejs`.

Tidak bisa berjalan

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220226-180838](https://user-images.githubusercontent.com/43334234/155840938-4ba520df-7c39-4174-8540-f6f8ada21285.png)
Why?

**Comment by DineshValor** [comment]
Brother you really want to run bot on termux? 🤐 Without spending extra efforts of internet! Why you didn't try out Ubuntu method in termux?

> ![Screenshot_Termux_20220226-180838](https://user-images.githubusercontent.com/43334234/155840938-4ba520df-7c39-4174-8540-f6f8ada21285.png) can't update or install

**Comment by ilhamn2405** [comment]
ubuntu
bash: /data/data/com.termux/files/usr/bin/ubuntu: Permission denied 

Di tolak

**Comment by DineshValor** [comment]
> ubuntu bash: /data/data/com.termux/files/usr/bin/ubuntu: Permission denied
> 
> Di tolak

What you trying to do with `ubuntu bash` command line?
Please always share a screenshot, its easier to understand where did error comes out!

**Comment by ilhamn2405** [comment]
![Uploading Screenshot_Termux_20220227-135354.png…]()

**Comment by DineshValor** [comment]
@ilhamn2405 screenshot didn't appeared in last comment! Did you tag some other screenshot or what?
![Screenshot_20220227-123317](https://user-images.githubusercontent.com/98645523/155872128-9fa8b701-6976-4a68-8923-3297a8cf252c.jpg)

**Comment by DineshValor** [comment]
> ![Screenshot_Termux_20220226-001630](https://user-images.githubusercontent.com/43334234/155759029-916d03d2-1cf0-4d2b-9d7f-dce2b2540584.png) Mengapa saya sqan menggunakan multi perangkat seperti ini bang?

Download from below link, Extract and copy `node_modules` into `games-wabot*', then try to run games-wabot.
https://drive.google.com/file/d/1Ydcjt3PnGiOr9vL66dFC11V0sEywJb32/view?usp=drivesdk

**Comment by DineshValor** [comment]
> ![Screenshot_Termux_20220226-001630](https://user-images.githubusercontent.com/43334234/155759029-916d03d2-1cf0-4d2b-9d7f-dce2b2540584.png) Mengapa saya sqan menggunakan multi perangkat seperti ini bang?

Re-write/replace this dependency code line https://github.com/BochilGaming/games-wabot/blob/dbf7b55f614f7eb104181f04fd6a4dd4318b2e51/package.json#L42 with this https://github.com/DineshValor/valor/blob/a01c80793a7e1c3f82cbded5e1b3279fdd2f9bfe/package.json#L45

Now follow below mentioned steps using original termux apk.
$ git clone <your edited repo link>
$ cd games-wabot
$ yarn
$ node .

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220302-060924](https://user-images.githubusercontent.com/43334234/156264377-5893be7e-5cf5-4c39-a6ab-66f72e4269d2.png)
why is it like this? I immediately tried npm install @adiwajshing/baileys-md but error

**Comment by DineshValor** [comment]
> ![Screenshot_Termux_20220302-060924](https://user-images.githubusercontent.com/43334234/156264377-5893be7e-5cf5-4c39-a6ab-66f72e4269d2.png) why is it like this? I immediately tried npm install @adiwajshing/baileys-md but error

I already applied a pull request to fix termux issue into @BochilGaming repo `games-wabot/multi-device`.
Unless he accept the pull request, you can follow this repo installation process.
https://github.com/DineshValor/valor

**Comment by DineshValor** [comment]
> ![Screenshot_Termux_20220302-060924](https://user-images.githubusercontent.com/43334234/156264377-5893be7e-5cf5-4c39-a6ab-66f72e4269d2.png) why is it like this? I immediately tried npm install @adiwajshing/baileys-md but error

If you want to run bot badly on termux and neither able to resolve issue nor found any solution then you can may try this [`repo`](https://github.com/DineshValor/valor) steps, but I'm not sure these steps can work with other repo or not.

**Comment by BochilGaming** [comment]
this problem occurs because the script doesn't support multi device but it scans using multi device

**Comment by ilhamn2405** [comment]
> > ![Screenshot_Termux_20220302-060924](https://user-images.githubusercontent.com/43334234/156264377-5893be7e-5cf5-4c39-a6ab-66f72e4269d2.png)mengapa seperti ini? Saya langsung mencoba npm install @adiwajshing/baileys-md tapi error
> 
> Jika Anda ingin menjalankan bot dengan buruk di termux dan tidak dapat menyelesaikan masalah atau menemukan solusi apa pun, Anda dapat mencoba [`repo`](https://github.com/DineshValor/valor)langkah ini, tetapi saya tidak yakin langkah ini dapat berfungsi dengan repo lain atau tidak.

good, the source code is working fine

**Comment by DineshValor** [comment]
> > > ![Screenshot_Termux_20220302-060924](https://user-images.githubusercontent.com/43334234/156264377-5893be7e-5cf5-4c39-a6ab-66f72e4269d2.png)mengapa seperti ini? Saya langsung mencoba npm install @adiwajshing/baileys-md tapi error
> > 
> > 
> > Jika Anda ingin menjalankan bot dengan buruk di termux dan tidak dapat menyelesaikan masalah atau menemukan solusi apa pun, Anda dapat mencoba [`repo`](https://github.com/DineshValor/valor)langkah ini, tetapi saya tidak yakin langkah ini dapat berfungsi dengan repo lain atau tidak.
> 
> good, the source code is working fine

I recommend to install nodejs-lts by using given below command in termux
$ pkg install nodejs-lts

**Comment by DineshValor** [comment]
> > > > ![Screenshot_Termux_20220302-060924](https://user-images.githubusercontent.com/43334234/156264377-5893be7e-5cf5-4c39-a6ab-66f72e4269d2.png)mengapa seperti ini? Saya langsung mencoba npm install @adiwajshing/baileys-md tapi error
> > > 
> > > 
> > > Jika Anda ingin menjalankan bot dengan buruk di termux dan tidak dapat menyelesaikan masalah atau menemukan solusi apa pun, Anda dapat mencoba [`repo`](https://github.com/DineshValor/valor)langkah ini, tetapi saya tidak yakin langkah ini dapat berfungsi dengan repo lain atau tidak.
> > 
> > 
> > good, the source code is working fine
> 
> I recommend to install nodejs-lts by using given below command in termux $ pkg install nodejs-lts

Nodejs-lts is the stable version of Nodejs, and support all bots script fine.

**Comment by botstylee** [comment]
> ![Screenshot_Termux_20220302-060924](https://user-images.githubusercontent.com/43334234/156264377-5893be7e-5cf5-4c39-a6ab-66f72e4269d2.png) why is it like this? I immediately tried npm install @adiwajshing/baileys-md but error

Modul Lo gak kebaca bang

**Comment by DineshValor** [comment]
> Coba dah npm install @adiwajshing/baileys-md

There is no such repo present at  adiwajshing/baileys-md
