### ISSUE TITLE
[10 April 2022] All Not Working `/commands` List Here!

### ISSUE THREAD

**Issue by DineshValor** [BochilGaming/games-wabot#247]
***This List keep up-to-date with all not working command list periodically. So before posting `New BUG`, checkout this issue #247***

=========================================
**Not Working Commands:**
Here,
/ = ${usedPrefix}

`/enable antitoxic` & `/disable antitoxic`

`/enable autolevelup` & `disable autolevelup`

`/enable detect` & `disable detect`

`/enable document` & `/disable document`

`/enable whitelistmycontacts` & `/disable whitelistmycontacts`

`/disable nyimak` - not working, but `/enable nyimak` - working

`/disable pconly` - not working, but `/enable pconly` - working

`/disable swonly` - not working but `/enable swonly` - working

=========================================

=> more cmd test, more outcome of working or not.

*Note: Keep update not working commands here.*

**Comment by BochilGaming** [comment]
> _**This List keep up-to-date with all not working command list. So before posting `New BUG`, checkout this issue #247**_
> 
> **Not Working Commands:** `/enable whitelistmycontacts` `/enable autolevelup` `/enable detect` `/enable antilink` `/okick`
> 
> => more cmd test, more outcome of working or not.
> 
> _Note: Keep update not working commands here._

Are you sure /okick not working?

**Comment by DineshValor** [comment]
> > _**This List keep up-to-date with all not working command list. So before posting `New BUG`, checkout this issue #247**_
> > **Not Working Commands:** `/enable whitelistmycontacts` `/enable autolevelup` `/enable detect` `/enable antilink` `/okick`
> > => more cmd test, more outcome of working or not.
> > _Note: Keep update not working commands here._
> 
> Are you sure /okick not working?

Will cross verify it after college exam over.

**Comment by DineshValor** [comment]
> > _**This List keep up-to-date with all not working command list. So before posting `New BUG`, checkout this issue #247**_
> > **Not Working Commands:** `/enable whitelistmycontacts` `/enable autolevelup` `/enable detect` `/enable antilink` `/okick`
> > => more cmd test, more outcome of working or not.
> > _Note: Keep update not working commands here._
> 
> Are you sure /okick not working?

Nope, not working, Crossed check now.
![Screenshot_20220228-142714](https://user-images.githubusercontent.com/98645523/155953885-b0c91b16-7853-4871-abc1-31da8ff66896.jpg)

**Comment by DineshValor** [comment]
> > _**This List keep up-to-date with all not working command list. So before posting `New BUG`, checkout this issue #247**_
> > **Not Working Commands:** `/enable whitelistmycontacts` `/enable autolevelup` `/enable detect` `/enable antilink` `/okick`
> > => more cmd test, more outcome of working or not.
> > _Note: Keep update not working commands here._
> 
> Are you sure /okick not working?

/okick Working now itself, maybe bug cause due to whatsapp beta or baileys side.

**Comment by BochilGaming** [comment]
> > > _**This List keep up-to-date with all not working command list. So before posting `New BUG`, checkout this issue #247**_
> > > **Not Working Commands:** `/enable whitelistmycontacts` `/enable autolevelup` `/enable detect` `/enable antilink` `/okick`
> > > => more cmd test, more outcome of working or not.
> > > _Note: Keep update not working commands here._
> > 
> > 
> > Are you sure /okick not working?
> 
> /okick Working now itself, maybe bug cause due to whatsapp beta or baileys side. ![Screenshot_20220314-165138](https://user-images.githubusercontent.com/98645523/158164467-5f18971d-028e-4145-aac5-7388d42214a3.jpg)

no, it's a bug because i added forgot mentionedJid in the serialize message

**Comment by DineshValor** [comment]
> > > > _**This List keep up-to-date with all not working command list. So before posting `New BUG`, checkout this issue #247**_
> > > > **Not Working Commands:** `/enable whitelistmycontacts` `/enable autolevelup` `/enable detect` `/enable antilink` `/okick`
> > > > => more cmd test, more outcome of working or not.
> > > > _Note: Keep update not working commands here._
> > > 
> > > 
> > > Are you sure /okick not working?
> > 
> > 
> > /okick Working now itself, maybe bug cause due to whatsapp beta or baileys side. ![Screenshot_20220314-165138](https://user-images.githubusercontent.com/98645523/158164467-5f18971d-028e-4145-aac5-7388d42214a3.jpg)
> 
> no, it's a bug because i added forgot mentionedJid in the serialize message

Oh great
