### ISSUE TITLE
Owner ga kebaca

### ISSUE THREAD

**Issue by Udangkering** [BochilGaming/games-wabot#248]
Jika owner menggunakan WhatsApp bussines maka fitur /owner tidak bisa digunakan. 
![IMG_20220228_033754](https://user-images.githubusercontent.com/88819514/155899145-97503a18-4dd6-425c-9861-595e9f8b7ead.jpg)

**Comment by Udangkering** [comment]
Oh iya ini yang multidevice

**Comment by BochilGaming** [comment]
> Oh iya ini yang multidevice

Send config.js mu

**Comment by Udangkering** [comment]
> > Oh iya ini yang multidevice
> 
> Send config.js mu

Ga ada yang beda sih, cuma ganti nomor owner yg di list ketiga jadi nomor ku yg pake wa bussines.

**Comment by BochilGaming** [comment]
> > > Oh iya ini yang multidevice
> > 
> > 
> > Send config.js mu
> 
> Ga ada yang beda sih, cuma ganti nomor owner yg di list ketiga jadi nomor ku yg pake wa bussines.

Share aja,  mungkin ngubah mu salah atau gimana

**Comment by BochilGaming** [comment]
Ok,  nanti ku fix :)

**Comment by DineshValor** [comment]
Can

> Jika owner menggunakan WhatsApp bussines maka fitur /owner tidak bisa digunakan. ![IMG_20220228_033754](https://user-images.githubusercontent.com/88819514/155899145-97503a18-4dd6-425c-9861-595e9f8b7ead.jpg)

Can you check again, because today i just installed Whatsapp Business to test that bug, but didn't find any error.
![Screenshot_20220302-075736](https://user-images.githubusercontent.com/98645523/156283003-642f7d58-5f21-4a3b-b661-0bff2830e42a.jpg)

**Comment by Udangkering** [comment]
> Can
> 
> > Jika owner menggunakan WhatsApp bussines maka fitur /owner tidak bisa digunakan. ![IMG_20220228_033754](https://user-images.githubusercontent.com/88819514/155899145-97503a18-4dd6-425c-9861-595e9f8b7ead.jpg)
> 
> Can you check again, because today i just installed Whatsapp Business to test that bug, but didn't find any error. ![Screenshot_20220302-075736](https://user-images.githubusercontent.com/98645523/156283003-642f7d58-5f21-4a3b-b661-0bff2830e42a.jpg)

I don't mean the bot that uses wa business but if the owner uses wa bussines.

**Comment by DineshValor** [comment]
> > Can
> > > Jika owner menggunakan WhatsApp bussines maka fitur /owner tidak bisa digunakan. ![IMG_20220228_033754](https://user-images.githubusercontent.com/88819514/155899145-97503a18-4dd6-425c-9861-595e9f8b7ead.jpg)
> > 
> > 
> > Can you check again, because today i just installed Whatsapp Business to test that bug, but didn't find any error. ![Screenshot_20220302-075736](https://user-images.githubusercontent.com/98645523/156283003-642f7d58-5f21-4a3b-b661-0bff2830e42a.jpg)
> 
> I don't mean the bot that uses wa business but if the owner uses wa bussines.

Yes, i tried bot setup on WA Business, and both user and owner able to use `/owner`.

**Comment by BochilGaming** [comment]
> > > Can
> > > > Jika owner menggunakan WhatsApp bussines maka fitur /owner tidak bisa digunakan. ![IMG_20220228_033754](https://user-images.githubusercontent.com/88819514/155899145-97503a18-4dd6-425c-9861-595e9f8b7ead.jpg)
> > > 
> > > 
> > > Can you check again, because today i just installed Whatsapp Business to test that bug, but didn't find any error. ![Screenshot_20220302-075736](https://user-images.githubusercontent.com/98645523/156283003-642f7d58-5f21-4a3b-b661-0bff2830e42a.jpg)
> > 
> > 
> > I don't mean the bot that uses wa business but if the owner uses wa bussines.
> 
> Yes, i tried bot setup on WA Business, and both user and owner able to use `/owner`.

if owner bussines and have description, it will give error

**Comment by DineshValor** [comment]
> > > > Can
> > > > > Jika owner menggunakan WhatsApp bussines maka fitur /owner tidak bisa digunakan. ![IMG_20220228_033754](https://user-images.githubusercontent.com/88819514/155899145-97503a18-4dd6-425c-9861-595e9f8b7ead.jpg)
> > > > 
> > > > 
> > > > Can you check again, because today i just installed Whatsapp Business to test that bug, but didn't find any error. ![Screenshot_20220302-075736](https://user-images.githubusercontent.com/98645523/156283003-642f7d58-5f21-4a3b-b661-0bff2830e42a.jpg)
> > > 
> > > 
> > > I don't mean the bot that uses wa business but if the owner uses wa bussines.
> > 
> > 
> > Yes, i tried bot setup on WA Business, and both user and owner able to use `/owner`.
> 
> if owner bussines and have description, it will give error



> > > > Can
> > > > > Jika owner menggunakan WhatsApp bussines maka fitur /owner tidak bisa digunakan. ![IMG_20220228_033754](https://user-images.githubusercontent.com/88819514/155899145-97503a18-4dd6-425c-9861-595e9f8b7ead.jpg)
> > > > 
> > > > 
> > > > Can you check again, because today i just installed Whatsapp Business to test that bug, but didn't find any error. ![Screenshot_20220302-075736](https://user-images.githubusercontent.com/98645523/156283003-642f7d58-5f21-4a3b-b661-0bff2830e42a.jpg)
> > > 
> > > 
> > > I don't mean the bot that uses wa business but if the owner uses wa bussines.
> > 
> > 
> > Yes, i tried bot setup on WA Business, and both user and owner able to use `/owner`.
> 
> if owner bussines and have description, it will give error

Nothing happened from my side with every thing insert in business like (Catalogue, description, etec)

![Screenshot_20220302-144636](https://user-images.githubusercontent.com/98645523/156332109-52a6bd00-7b0e-439a-96db-4dd9b63a94d2.jpg)

Everything think fine with `/onwer` from my side.
![Screenshot_20220302-144728](https://user-images.githubusercontent.com/98645523/156332125-0e4cc02c-c4c7-4bc0-82cf-ab4eeded8c2f.jpg)

**Comment by BochilGaming** [comment]
Fix :)
