### ISSUE TITLE
Node .

### ISSUE THREAD

**Issue by ilhamn2405** [BochilGaming/games-wabot#259]
![Uploading Screenshot_Termux_20220309-013804.png…]()
Saya sudah menginstal module, setelah mau menjalankan node . Tiba" seperti ini bang

**Comment by ilhamn2405** [comment]
![Uploading Screenshot_Termux_20220309-013804.png…]()

**Comment by BochilGaming** [comment]
gk bisa dibuka screnshoot nya

**Comment by ilhamn2405** [comment]
![Uploading Screenshot_Termux_20220309-013804.png…]()

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220309-013804](https://user-images.githubusercontent.com/43334234/157424700-53f22040-e556-4182-a3f1-89d64f43de63.png)

**Comment by BochilGaming** [comment]
Node versi?, dan apakah pas npm i ada error?

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220309-204122](https://user-images.githubusercontent.com/43334234/157453429-d5477f1e-a322-4910-90f5-318b7167780b.png)

**Comment by BochilGaming** [comment]
```sh
npm i --force --legacy-peer-deps
```

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220311-060347](https://user-images.githubusercontent.com/43334234/157770096-654b0fdf-c830-4544-be34-220964e19cc9.png)
Udah mas, tapi sama aja

**Comment by DineshValor** [comment]
> 
**For Multi-device branch Error**
1. Fork the Repo.
2. Replace line 42 in `package.json` (multi-device branch)
https://github.com/BochilGaming/games-wabot/blob/3ea32495bb7a37bf3131e3881387b3914d991e2d/package.json#L42
With below line
```
        "@adiwajshing/baileys": "^4.0.1",
        "@adiwajshing/keyed-db": "^0.2.4",
```
3. Save Commit Changes.
4. Open Termux and type below commands
```
$ git clone https://github.com/BochilGaming/games-wabot -b multi-device
$ cd games-wabot
$ yarn
$ node .
```
