### ISSUE TITLE
Fitur chat pribadi ke nomor yang di tentukan

### ISSUE THREAD

**Issue by Udangkering** [BochilGaming/games-wabot#261]
Request fitur yang bisa kirim pesan pribadi ke nomor yang dituju ada ga?

**Comment by DineshValor** [comment]
Yes, similar one with name Broadcast

**Comment by akmallxx** [comment]
> Request fitur yang bisa kirim pesan pribadi ke nomor yang dituju ada ga?

mkasud?

**Comment by BochilGaming** [comment]
> Request fitur yang bisa kirim pesan pribadi ke nomor yang dituju ada ga?

knp gk langsung chat ke dia :v

**Comment by Udangkering** [comment]
> > Request fitur yang bisa kirim pesan pribadi ke nomor yang dituju ada ga?
> 
> knp gk langsung chat ke dia :v

Banyak nomor sekaligus yg ditentuin sendiri nomornya gitu :v

**Comment by BochilGaming** [comment]
> > > Request fitur yang bisa kirim pesan pribadi ke nomor yang dituju ada ga?
> > 
> > 
> > knp gk langsung chat ke dia :v
> 
> Kirim ke Banyak nomor sekaligus yg ditentuin sendiri nomornya gitu :v

nanti ke banned bot nya, tapi kan udh ada fitur broadcast walaupun gk bisa nomor yang kamu tentuin sendiri

**Comment by Udangkering** [comment]
> > > > Request fitur yang bisa kirim pesan pribadi ke nomor yang dituju ada ga?
> > > 
> > > 
> > > knp gk langsung chat ke dia :v
> > 
> > 
> > Kirim ke Banyak nomor sekaligus yg ditentuin sendiri nomornya gitu :v
> 
> nanti ke banned bot nya, tapi kan udh ada fitur broadcast walaupun gk bisa nomor yang kamu tentuin sendiri

Baiklah kalau begitu
