### ISSUE TITLE
[MD] Issue with Math.js Answer!

### ISSUE THREAD

**Issue by DineshValor** [BochilGaming/games-wabot#263]
**Describe the bug**
Everything working except answer reply.
Each time its show timeout even answered already done but bot unable to receive reply answer by user.

**Comment by BochilGaming** [comment]
> **Describe the bug** Everything working except answer reply. Each time its show timeout even answered already done but bot unable to receive reply answer by user.

maybe the conn.math object is missing

**Comment by DineshValor** [comment]
> 

🥲

**Comment by DineshValor** [comment]
Answer not working
![Screenshot_20220325-014644](https://user-images.githubusercontent.com/98645523/160002588-f434b627-526e-4aa3-998f-d3c9fcdc4fa0.jpg)
