### ISSUE TITLE
Izin

### ISSUE THREAD

**Issue by botstylee** [BochilGaming/games-wabot#271]
Bruh izin download multi device punya mu mau ku kembangkan di repo github ku ya

**Comment by BochilGaming** [comment]
> Bruh izin download multi device punya mu mau ku kembangkan di repo github ku ya

recode aja namanya open source

**Comment by botstylee** [comment]
> > Bruh izin download multi device punya mu mau ku kembangkan di repo github ku ya
> 
> recode aja namanya open source

Agak susah juga SC md Lo yg baru itu, beda modul sama yg SC ini ya ?
