### ISSUE TITLE
Whyy??

### ISSUE THREAD

**Issue by itsmedell** [BochilGaming/games-wabot#274]
![Screenshot_20220316_133231](https://user-images.githubusercontent.com/87001693/158523324-dd6e6431-eefd-420a-bbad-54a8a5e541a3.jpg)
? 

Kenapa nih?

**Comment by itsmedell** [comment]
> 

Multi-device branch

**Comment by Jauhariq** [comment]
> > 
> 
> Multi-device branch

Upgrade ramnya, makin banyak yang make bot makin bengkak ramnya apalagi ga dimatiin berhari hari, pake heroku ada batasan ramnya. Gua saranin lu pake rdp/vps atau hosting lain yang pake pterodactyl.
