### ISSUE TITLE
Cara Add Database Otomatis ke Mongodb gimana?

### ISSUE THREAD

**Issue by Bintangp02** [BochilGaming/games-wabot#275]
**Cara Add Data base Otomatis ke mongodb Gimana?**
_Makasih_

**Comment by NevtBotz** [comment]
Yntkts

**Comment by BochilGaming** [comment]
> **Cara Add Data base Otomatis ke mongodb Gimana?** _Makasih_

--db linkmongodbmu 
taruh di startup

**Comment by Udangkering** [comment]
> > **Cara Add Data base Otomatis ke mongodb Gimana?** _Makasih_
> 
> --db linkmongodbmu taruh di startup

index.js --db linknya
Gitu?

**Comment by NevtBotz** [comment]
Di procfile worker: npm start  --db 'link mongodb'
MAFF KLO SALAH🗿

**Comment by Udangkering** [comment]
![Screenshot_2022-03-17-16-09-40-07](https://user-images.githubusercontent.com/88819514/158776873-bd6cbc60-dff5-4671-911e-e5ad6abad0c6.jpg)
Pilih yang mana ya?

**Comment by BochilGaming** [comment]
> > > **Cara Add Data base Otomatis ke mongodb Gimana?** _Makasih_
> > 
> > 
> > --db linkmongodbmu taruh di startup
> 
> index.js --db linknya Gitu?

node index --db linknya

**Comment by BochilGaming** [comment]
> Di procfile worker: npm start --db 'link mongodb' MAFF KLO SALAH🗿

kalau run di heroku bisa taruh disitu

**Comment by NevtBotz** [comment]
Iyah

**Comment by Bintangp02** [comment]
Oke pulang jumat'an langsung coba🗿

**Comment by Bintangp02** [comment]
> > > > **Cara Add Data base Otomatis ke mongodb Gimana?** _Makasih_
> > > 
> > > 
> > > --db linkmongodbmu taruh di startup
> > 
> > 
> > index.js --db linknya Gitu?
> 
> node index --db linknya

Format paswd nya  ```<password>``` ganti ngk? Atau biarkan gitu aja Start 
```node index --db (link nye)```

**Comment by Jauhariq** [comment]
> > > > > **Cara Add Data base Otomatis ke mongodb Gimana?** _Makasih_
> > > > 
> > > > 
> > > > --db linkmongodbmu taruh di startup
> > > 
> > > 
> > > index.js --db linknya Gitu?
> > 
> > 
> > node index --db linknya
> 
> Format paswd nya `<password>` ganti ngk? Atau biarkan gitu aja Start `node index --db (link nye)`

Ganti pw sama myfirstporject juga ganti ke nama projectlu

**Comment by Bintangp02** [comment]
[**makasih dah mau bantu semuanya, kalau ada error open!**](https://github.com/BochilGaming/games-wabot#makasih-sudah-bantu-gw-bang-semoga-lancar-aminn-semua-yang-diminta-terkabul-aamin)
