### ISSUE TITLE
[HELP] AntiSpam Admin Suport

### ISSUE THREAD

**Issue by lilnext01** [BochilGaming/games-wabot#28]
Bagaimana caranya agar Antispam tidak mendeteksi Spam dari pengguna yang merupakan administrator grup?

**Comment by BochilGaming** [comment]
```
let groupMetadata = m.isGroup ? await this.groupMetadata(m.chat) : {}   
let participants = m.isGroup ? groupMetadata.participants : []      
let user = m.isGroup ? participants.find(u => u.jid == m.sender) : {}          
let isAdmin = user.isAdmin || user.isSuperAdmin || false 

if (isAdmin) return
```

Tambahkan itu di bawah [line ini](https://github.com/BochilGaming/games-wabot/blob/9a72458bb62cdcbf9204303f9fb15ae9077153cf/plugins/__antispam.js#L4)
