### ISSUE TITLE
Commonjs version? 

### ISSUE THREAD

**Issue by what-zit-tooyaa** [BochilGaming/games-wabot#280]

**Comment by BochilGaming** [comment]
Use ESM instead commonJS

**Comment by botstylee** [comment]
> Use ESM instead commonJS

Gw nyari yang commonjs ada gak bruh

**Comment by BochilGaming** [comment]
> > Use ESM instead commonJS
> 
> Gw nyari yang commonjs ada gak bruh

gk ada, tapi kalau kamu liat commit nya itu kan ada yang sebelum esm jadi ambil aja tapi pasti banyak error karena udh lama

**Comment by botstylee** [comment]
> 

Itu yang esm make metode gini
import fetch from 'node-fetch';

Apa gini
let fetch = await import("fetch")
