### ISSUE TITLE
Reconnect 

### ISSUE THREAD

**Issue by ilhamn2405** [BochilGaming/games-wabot#284]
![IMG_20220322_061905](https://user-images.githubusercontent.com/43334234/159378816-e416a41c-2a79-4fea-bd66-8ccf8d869d93.jpg)
Knpa setelah kehilangan koneksi sebentar, knpa gini bang?

**Comment by BochilGaming** [comment]
coba update ke baileys terbaru terus rescan

**Comment by ilhamn2405** [comment]
> coba update ke baileys terbaru terus rescan

Cara updatenya gmna?

**Comment by BochilGaming** [comment]
> > coba update ke baileys terbaru terus rescan
> 
> Cara updatenya gmna?

npm i github:adiwajshing/baileys

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220322-134926](https://user-images.githubusercontent.com/43334234/159423900-7d0fd6bf-a374-4e33-b266-2334ca87e028.png)
Gini bang

**Comment by DineshValor** [comment]
> 

Rescan the code, same happened with me now and simply go for new qrcode scan

**Comment by ilhamn2405** [comment]
> > 
> 
> Pindai ulang kodenya, hal yang sama terjadi dengan saya sekarang dan cukup lakukan pemindaian qrcode baru

I did the same thing many times
