### ISSUE TITLE
@adiwajshing/bailey's bug

### ISSUE THREAD

**Issue by Scooppt** [BochilGaming/games-wabot#30]
"@adiwajshing/baileys": "3.4.1"

This version is outdated. New version is 3.5.1 but this is not working with the bot, to sign up to whatsapp web.
Solution for now is to edit manually in version 3.4.1 the following file to increase whatsapp web version:
https://github.com/adiwajshing/Baileys/commit/1c8d7df829bb3893673ba893cbaae1144f09fe58

**Comment by BochilGaming** [comment]
> "@adiwajshing/baileys": "3.4.1"
> 
> This version is outdated. New version is 3.5.1 but this is not working with the bot, to sign up to whatsapp web.
> Solution for now is to edit manually in version 3.4.1 the following file to increase whatsapp web version:
> [adiwajshing/Baileys@1c8d7df](https://github.com/adiwajshing/Baileys/commit/1c8d7df829bb3893673ba893cbaae1144f09fe58)

Thank you for the information

**Comment by BochilGaming** [comment]
Fixx
