### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by ilhamn2405** [BochilGaming/games-wabot#300]
![Screenshot_WhatsApp_20220407-121137](https://user-images.githubusercontent.com/43334234/162124896-71992669-3e76-4a36-a41a-22ebef654965.png)
Functionnya apaan bang, gw mau tambahin addprem durasinya bisa di atur sesuka hati

**Comment by BochilGaming** [comment]
https://github.com/BochilGaming/games-wabot/blob/16d4ac2074018846aec59b30f19f52caff70dc48/lib/simple.js#L1236
 
Tinggal kalau ada Number tinggal .toMsString()

**Comment by ilhamn2405** [comment]
> https://github.com/BochilGaming/games-wabot/blob/16d4ac2074018846aec59b30f19f52caff70dc48/lib/simple.js#L1236
> 
> Tinggal kalau ada Number tinggal .toTimeString() Contoh
> 
> https://github.com/BochilGaming/games-wabot/blob/16d4ac2074018846aec59b30f19f52caff70dc48/plugins/rpg-adventure.js#L11

Number.prototype.toTimeString = function toTimeString() {
        // const milliseconds = this % 1000
        const seconds = Math.floor((this / 1000) % 60)
        const minutes = Math.floor((this / (60 * 1000)) % 60)
        const hours = Math.floor((this / (60 * 60 * 1000)) % 24)
        const days = Math.floor((this / (24 * 60 * 60 * 1000)))
        return (
            (days ? `${days} day(s) ` : '') +
            (hours ? `${hours} hour(s) ` : '') +
            (minutes ? `${minutes} minute(s) ` : '') +
            (seconds ? `${seconds} second(s)` : '')
        ).trim()
    }
    Number.prototype.getRandom = String.prototype.getRandom = Array.prototype.getRandom = getRandom
}

Segitu aja bang? Tempel di simple.js? Gw pake games-wabot biasa, bukan multi perangkat

**Comment by BochilGaming** [comment]
https://github.com/BochilGaming/games-wabot/blob/b3f857a5442bdae0f4dfa110234fad42676a28bf/plugins/adventure.js#L83#L89

https://github.com/BochilGaming/games-wabot/blob/b3f857a5442bdae0f4dfa110234fad42676a28bf/plugins/adventure.js#L5#L7

**Comment by ilhamn2405** [comment]
> https://github.com/BochilGaming/games-wabot/blob/b3f857a5442bdae0f4dfa110234fad42676a28bf/plugins/adventure.js#L83-L89
> 
> https://github.com/BochilGaming/games-wabot/blob/b3f857a5442bdae0f4dfa110234fad42676a28bf/plugins/adventure.js#L5-L7

![1649431025-picsay](https://user-images.githubusercontent.com/43334234/162472670-129d70a2-75b1-47bd-9765-512c0e6e84be.jpg)

Sorry bang kalau saya kurang paham:v ini kalau merubah angka jadi hari gmna ya:v

**Comment by ilhamn2405** [comment]
Saya ganti ke multi perangkat, ternyata lebih enak:v
