### ISSUE TITLE
Tidak bisa node .

### ISSUE THREAD

**Issue by Andika856** [BochilGaming/games-wabot#305]
![Screenshot_2022-04-10-12-36-09-88_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/78887981/162603049-f78378d2-09e0-488d-80fe-0f2ea637893c.jpg)

**Comment by Andika856** [comment]
Ada yg bisa bantu?

**Comment by BochilGaming** [comment]
node version?

**Comment by Andika856** [comment]
> node version?

Nodejs?

**Comment by Andika856** [comment]
12.22.5~dfsg-5ubuntu1

**Comment by Andika856** [comment]
![Screenshot_2022-04-11-13-56-28-34_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/78887981/162681989-f2cc20b2-41f3-4607-ba11-0a7b1445d4de.jpg)
Uh
