### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Netshh** [BochilGaming/games-wabot#306]
Saya pemula nyoba pake replit tapi pas instal kok module not found ya? Ada yang bisa bantu?

**Comment by Netshh** [comment]
![Uploading Screenshot_2022-04-10-13-42-35-769_com.android.chrome.jpg…]()

**Comment by Netshh** [comment]
![Screenshot_2022-04-10-13-42-35-769_com android chrome](https://user-images.githubusercontent.com/93586570/162606194-2244f7c7-7f6b-456f-9f15-790e18622e09.jpg)

**Comment by BochilGaming** [comment]
file index.js, package.json gk ada, mungkin corupt atau gimana filenya

**Comment by aniq12** [comment]
udh fix kan, close aja

**Comment by BochilGaming** [comment]
> udh fix kan, close aja

Nunggu response dari pembuat issue :v

**Comment by aniq12** [comment]
> > udh fix kan, close aja
> 
> Nunggu response dari pembuat issue :v

udh cuy maren gw bantu di wa
