### ISSUE TITLE
Req Md:

### ISSUE THREAD

**Issue by Natx-C** [BochilGaming/games-wabot#307]
tambahin getdb bang mwhehe,

**Comment by aniq12** [comment]
getdb kek mana

**Comment by Natx-C** [comment]
> getdb kek mana

https://github.com/Nurutomo/wabot-aq/pull/1054#issue-1183568648
tapi pas ane nyoba, eror ora mudeng aku

**Comment by aniq12** [comment]
> > getdb kek mana
> 
> [Nurutomo/wabot-aq#1054 (comment)](https://github.com/Nurutomo/wabot-aq/pull/1054#issue-1183568648) tapi pas ane nyoba, eror ora mudeng aku

error nya?

**Comment by aniq12** [comment]
blm ke upload..

**Comment by Natx-C** [comment]
![Uploading Screenshot_2022-04-11-21-19-44-13.jpg…]()

**Comment by aniq12** [comment]
mana we :v

**Comment by Natx-C** [comment]
> mana we :v

kaga ke upload wkwk :v
https://telegra.ph/file/0c51a1b04865a6c08f108.jpg

**Comment by aniq12** [comment]
> > mana we :v
> 
> kaga ke upload wkwk :v https://telegra.ph/file/0c51a1b04865a6c08f108.jpg

`import fs from 'fs'
let handler  = async (m, { conn, text }) => {
m.reply('Tunggu Sebentar, Proses Getting File database.json')
let db = fs.readFileSync('./database.json')
conn.sendFile(m.chat, db, 'database.json', null, m)
}
handler.help = ['getdb','getdatabase'].map(v => v + ' <teks>')
handler.tags = ['owner']
handler.command = /^(db|getdb)$/i
handler.owner = true
export default handler`

**Comment by Natx-C** [comment]
> > > mana we :v
> > 
> > 
> > kaga ke upload wkwk :v https://telegra.ph/file/0c51a1b04865a6c08f108.jpg
> 
> `import fs from 'fs'\nlet handler = async (m, { conn, text }) => { m.reply('Tunggu Sebentar, Proses Getting File database.json') let db = fs.readFileSync('./database.json') conn.sendFile(m.chat, db, 'database.json', null, m) } handler.help = ['getdb','getdatabase'].map(v => v + ' <teks>') handler.tags = ['owner'] handler.command = /^(db|getdb)$/i handler.owner = true export default handler`

wokeh makasih tak coba sek bang

**Comment by Natx-C** [comment]
> > > mana we :v
> > 
> > 
> > kaga ke upload wkwk :v https://telegra.ph/file/0c51a1b04865a6c08f108.jpg
> 
> ```js
> import fs from 'fs'
> let handler  = async (m, { conn, text }) => {
>    m.reply('Tunggu Sebentar, Proses Getting File database.json')
>    let db = fs.readFileSync('./database.json')
>    conn.sendFile(m.chat, db, 'database.json', null, m)
> }
> handler.help = ['getdb','getdatabase'].map(v => v + ' <teks>')
> handler.tags = ['owner']
> handler.command = /^(db|getdb)$/i
> handler.owner = true
> export default handler
> ```

bisa bang, makasih ya ane close
https://telegra.ph/file/466fc219f569bccbb11c0.jpg
