### ISSUE TITLE
Kadang msg undefined dan kadang msg nya kasi dalam bentuk putih dan kadang muncul rejection error' gitu 

### ISSUE THREAD

**Issue by Andika856** [BochilGaming/games-wabot#308]
![Screenshot_2022-04-11-21-26-13-77_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/78887981/162761398-8aae6c23-473c-42c8-b6bb-911b640241bc.jpg)
![Screenshot_2022-04-11-21-25-33-23_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/78887981/162761412-47c5969e-bbbd-41d7-a970-84b530b147c2.jpg)

**Comment by Natx-C** [comment]
![Screenshot_2022-04-12-03-56-52-13_469d9a8fb01100be319306c44b95b80a](https://user-images.githubusercontent.com/83612604/162830825-11a2b7c1-2e76-44a4-9b03-71519195824e.jpg)
heroku lancar

**Comment by BochilGaming** [comment]
Kalau mtype ciphertext itu berarti baileys gagal decrpty message nya, jadi ya undefined. Terus "precondition required" itu bug dari baileys. Terus bagaimana cara mengurangi nya?, coba rescan supaya session nya masih fresh

**Comment by Andika856** [comment]
Oke bang
