### ISSUE TITLE
Ini kenapa ya

### ISSUE THREAD

**Issue by Udangkering** [BochilGaming/games-wabot#315]
![Screenshot_2022-04-16-19-41-33-09](https://user-images.githubusercontent.com/88819514/163675419-77272872-da35-4c7f-800c-ac1715b59630.jpg)

**Comment by BochilGaming** [comment]
Error, coba jalanin file test.js buat ngetahui dimana error nya

**Comment by Udangkering** [comment]
> Error, coba jalanin file test.js buat ngetahui dimana error nya

Ah iya ternyata ada fitur yang eror hehe , thanks
