### ISSUE TITLE
Ask 

### ISSUE THREAD

**Issue by peraaxd** [BochilGaming/games-wabot#316]
![IMG-20220416-WA0108](https://user-images.githubusercontent.com/71998161/163676304-45ffa3e7-6bdf-4f15-8890-7607b042584d.jpeg)

Numpang tanya bang ini kenapa ya?

**Comment by BochilGaming** [comment]
```js
const { MessageType } = (await import('@adiwajshing/baileys')).default
```
Coba itu?

**Comment by peraaxd** [comment]
> ```js
> const { MessageType } = (await import('@adiwajshing/baileys')).default
> ```
> 
> Coba itu?

Walah makasih bang 👍
