### ISSUE TITLE
Eror tiap 3 jam sekali

### ISSUE THREAD

**Issue by Udangkering** [BochilGaming/games-wabot#327]
![Screenshot_2022-04-26-15-36-14-04](https://user-images.githubusercontent.com/88819514/165259620-aa7b0f1d-0933-4747-a809-4503a0c6530e.jpg)
Ini kenapa ya tiap 3 jam sekali gini, kondisi bot keliatan online tapi centang satu dan harus rescan kalo mau jalan lagi

Multidevice

**Comment by Rizxyu** [comment]
Kyk punya gw tapi sekarang jarang, keknya botlu sering dispam kali jadinya sessionnya mental
