### ISSUE TITLE
Fitur tidak muncul

### ISSUE THREAD

**Issue by Rhosad29** [BochilGaming/games-wabot#334]
Bang, kenapa ya ada fitur yg gak muncul meski sudah di folder plugins ?
seperti yg barusan di update alquran, zodiak, dll itu tidak muncul waktu pakai yg multi-device

**Comment by Jauhariq** [comment]
Isi codenya udah bener belom? Kalo udah bener pasti muncul

**Comment by BochilGaming** [comment]
> Isi codenya udah bener belom? Kalo udah bener pasti muncul

Iy, mungkin aja code mu masih pakek cjs sedangkan multi device sudah tidak support cjs tapi support esm

**Comment by Rhosad29** [comment]
convertnya gimana bang ?
masih newbie 🙏🙏

**Comment by Rhosad29** [comment]
> Isi codenya udah bener belom? Kalo udah bener pasti muncul

saya ambil dari plugins main

**Comment by BochilGaming** [comment]
> convertnya gimana bang ? masih newbie 🙏🙏

ubah semua require ke import atau kalau gk bisa ubah ke import, paling atas file kasih 
```js
const require = global.__require(import.meta.url)
```
terus jangan lupa ubah `module.exports =` ke `export`
untuk lebih jelasnya bisa liat file yang udh ada di folder plugins

**Comment by Rhosad29** [comment]
sudah semua kalau let required diganti import.
sama module.eports diganti export default

**Comment by BochilGaming** [comment]
> sudah semua kalau let required diganti import. sama module.eports diganti export default

bisa post kodemu biar kita bisa liat?

**Comment by Rhosad29** [comment]
> > sudah semua kalau let required diganti import. sama module.eports diganti export default
> import fetch from 'node-fetch'
let handler = async (m, {conn,  args, usedPrefix, command }) => {

> bisa post kodemu biar kita bisa liat?

=============================
import fetch from 'node-fetch'
let handler = async (m, {conn,  args, usedPrefix, command }) => {

  if (!args[0]) throw `Use example ${usedPrefix}${command} 2 1\nMaka akan muncul surat Al-Baqarah Ayat 1`

    let res = await fetch(global.API('zahir', `/api/quran?surah=${args[0]}&ayat=1`, {}, 'apikey'))
    if (!res.ok) throw await res.json.message()
    let json = await res.json.result.data()
    if (!json.result.data.number) throw console.log()
    m.reply(m.chat, `
${json.result.data.text.arab}\n

${json.result.data.translation.id}\n
${readMore}
${json.result.data.tafsir.id}\n

( ${json.result.data.surah.name.transliteration.id} / ${json.result.data.surah.name.translation.id} )
`.trim())
    conn.sendFile(m.chat, json.result.data.audio.primary , '', m)
}
handler.help = ['surah <114> <1>']
handler.tags = ['quran']
handler.command = /^(surah)?$/i
export default = handler
============================================

**Comment by Jauhariq** [comment]
> 

```
import fetch from 'node-fetch'

let handler = async (m, { conn, args, usedPrefix, command }) => {
    if (!(args[0] || args[1])) throw `contoh:\n${usedPrefix + command} 1 2\n\nmaka hasilnya adalah surah Al-Fatihah ayat 2 beserta audionya, dan ayatnya 1 aja`
    if (isNaN(args[0]) || isNaN(args[1])) throw `contoh:\n${usedPrefix + command} 1 2\n\nmaka hasilnya adalah surah Al-Fatihah ayat 2 beserta audionya, dan ayatnya 1 aja`

    let res = await fetch(global.API('https://islamic-api-indonesia.herokuapp.com', '/api/data/quran', { surah: args[0], ayat: args[1] }))
    if (!res.ok) throw await res.text()
    let json = await res.json()
    let mes = `
${json.result.data.text.arab}
    
${json.result.data.translation.id}
( Q.S ${json.result.data.surah.name.transliteration.id} : ${json.result.data.number.inSurah} )
`.trim()
    m.reply(mes)
    conn.sendFile(m.chat, json.result.data.audio.primary, 'audio.mp3', '', m, 0, { mimetype: 'audio/mp4' })
}
handler.help = ['alquran <114> <1>']
handler.tags = ['islamic']
handler.command = /^(al)?quran$/i

export default handler
```

**Comment by Rhosad29** [comment]
> > 
> 
> ```js
> import fetch from 'node-fetch'
> 
> let handler = async (m, { conn, args, usedPrefix, command }) => {
>     if (!(args[0] || args[1])) throw `contoh:\n${usedPrefix + command} 1 2\n\nmaka hasilnya adalah surah Al-Fatihah ayat 2 beserta audionya, dan ayatnya 1 aja`
>     if (isNaN(args[0]) || isNaN(args[1])) throw `contoh:\n${usedPrefix + command} 1 2\n\nmaka hasilnya adalah surah Al-Fatihah ayat 2 beserta audionya, dan ayatnya 1 aja`
> 
>     let res = await fetch(global.API('https://islamic-api-indonesia.herokuapp.com', '/api/data/quran', { surah: args[0], ayat: args[1] }))
>     if (!res.ok) throw await res.text()
>     let json = await res.json()
>     let mes = `
> ${json.result.data.text.arab}
>     
> ${json.result.data.translation.id}
> ( Q.S ${json.result.data.surah.name.transliteration.id} : ${json.result.data.number.inSurah} )
> `.trim()
>     m.reply(mes)
>     conn.sendFile(m.chat, json.result.data.audio.primary, 'audio.mp3', '', m, 0, { mimetype: 'audio/mp4' })
> }
> handler.help = ['alquran <114> <1>']
> handler.tags = ['islamic']
> handler.command = /^(al)?quran$/i
> 
> export default handler
> ```

![IMG_20220525_052259](https://user-images.githubusercontent.com/105351770/170141839-e3c67e05-3e46-48e9-a33a-9e83a8224ce4.jpg)

Thanks bang, saya pelajari lagi 🙏
