### ISSUE TITLE
buat yg md, botnya ga respon

### ISSUE THREAD

**Issue by akmallxx** [BochilGaming/games-wabot#338]
mohon solusinya dong, padahal lognya aman2 aja

atau krn saya pakai wa bisnis?

**Comment by BochilGaming** [comment]
coba restart?, dan pastiin kalau tidak self/pconly/gconly. atau kalau kamu pakai mongodb coba tunggu karena bot nya gk bakal respon sebelum connect

**Comment by akmallxx** [comment]
blum diubah apa"nya, abis scan pas dites gk respon, dan udh dicoba di wa biasa jg sm aja

**Comment by BochilGaming** [comment]
1. Di log apakah terdapat error?
2. Apakah anda memakai mongodb?
3. Dimana anda menjalankan bot anda?
Coba restart mungkin membantu?

**Comment by Bintangp02** [comment]
> 1. Di log apakah terdapat [error](https://github.com/BochilGaming/games-wabot/issues/338)?
> 2. Apakah anda memakai mongodb?
> 3. Dimana anda menjalankan bot anda?
>    Coba restart mungkin membantu?


**hay, saya mengalami masalah sulit bagaimana cara mengatasi  hal seperti ini** 
```
{"level":30,"time":"2022-05-30T12:14:52.629Z","pid":565,"hostname":"8ebf9636d799","class":"baileys","msgAttrs":{"from":"6289647417373@s.whatsapp.net","type":"text","id":"83EE2B007090B36136A78E10F7BA610B","notify":"Bintangp02 XXI","t":"1653912892"},"retryCount":3,"msg":"sent retry receipt"}
```

**Comment by akmallxx** [comment]
> 1. Di log apakah terdapat error?
> 2. Apakah anda memakai mongodb?
> 3. Dimana anda menjalankan bot anda?
>    Coba restart mungkin membantu?

di log gada error, saya gk pakai mongodb, saya run di replit, sudah restart tpi sm aj

edit:
di log, command udh pke prefix kedetect extended text, dan ga respon

**Comment by BochilGaming** [comment]
> > 1. Di log apakah terdapat error?
> > 2. Apakah anda memakai mongodb?
> > 3. Dimana anda menjalankan bot anda?
> >    Coba restart mungkin membantu?
> 
> di log gada error, saya gk pakai mongodb, saya run di replit, sudah restart tpi sm aj
> 
> edit: di log, command udh pke prefix kedetect extended text, dan ga respon

command nya berwarna kuning di log?

**Comment by BochilGaming** [comment]
> > 1. Di log apakah terdapat [error](https://github.com/BochilGaming/games-wabot/issues/338)?
> > 2. Apakah anda memakai mongodb?
> > 3. Dimana anda menjalankan bot anda?
> >    Coba restart mungkin membantu?
> 
> **hay, saya mengalami masalah sulit bagaimana cara mengatasi hal seperti ini**
> 
> ```
> {"level":30,"time":"2022-05-30T12:14:52.629Z","pid":565,"hostname":"8ebf9636d799","class":"baileys","msgAttrs":{"from":"6289647417373@s.whatsapp.net","type":"text","id":"83EE2B007090B36136A78E10F7BA610B","notify":"Bintangp02 XXI","t":"1653912892"},"retryCount":3,"msg":"sent retry receipt"}
> ```

baileys gagal decrypt message, sehingga baileys mengulangi decrypt message dan gagal lagi

**Comment by akmallxx** [comment]
> > > 1. Di log apakah terdapat error?
> > > 2. Apakah anda memakai mongodb?
> > > 3. Dimana anda menjalankan bot anda?
> > >    Coba restart mungkin membantu?
> > 
> > 
> > di log gada error, saya gk pakai mongodb, saya run di replit, sudah restart tpi sm aj
> > edit: di log, command udh pke prefix kedetect extended text, dan ga respon
> 
> command nya berwarna kuning di log?

seingatku putih

edit:
btw saya run di replit, apakah versi nodejs di replit terlalu jadul? saya sdh menggunakan nix beta
