### ISSUE TITLE
How to send ListMessage

### ISSUE THREAD

**Issue by Alizee187** [BochilGaming/games-wabot#344]
i want to migrate my old pluggins here in MD, but i use a loot listMessage, and dont see "**case MessageType.listMessage:
          m.listMessage = WAMessageProto.ListMessage.fromObject(message)**" in simple.js (that menas, the bot not know when i use 
          **await conn.sendListMessage(m.chat, { buttonText: 'Menu del casino!', description: 'MeduS.A-bot | *CASINO*\n\n Hola! Bienvenido al casino La medusa... toca el boton de abajo, y te dara varios comandos del casino!', title: 'CASINO!' },**

what i can do? (bad english, sorry)

**Comment by BochilGaming** [comment]
https://github.com/adiwajshing/Baileys#non-media-messages
