### ISSUE TITLE
[md] tiktok error 

### ISSUE THREAD

**Issue by Uzoy** [BochilGaming/games-wabot#346]
![image](https://user-images.githubusercontent.com/78887981/171303882-1b49e4b1-e2ed-43d6-b38d-1823b90479ec.png)

**Comment by BochilGaming** [comment]
cc @bochilteam/scraper

**Comment by Rhosad29** [comment]
punya saya bisa bang, ada yg dikurangi.

comment nulis code gimana ya ? ✌️

**Comment by Rhosad29** [comment]
const { author: { nickname }, video, description } = await tiktokdl(args[0])
    const url = video.no_watermark || video.no_watermark2 || video.no_watermark_raw


itu aja yg diganti

**Comment by Uzoy** [comment]
> ```
> const { author: { nickname }, video, description } = await tiktokdl(args[0])
> const url = video.no_watermark || video.no_watermark2 || video.no_watermark_raw
> ```
> 
> itu aja yg diganti

makasih bang :D

**Comment by Rhosad29** [comment]
oke bang :v

**Comment by LESOTOLE** [comment]
> ```
> const { author: { nickname }, video, description } = await tiktokdl(args[0])
> const url = video.no_watermark || video.no_watermark2 || video.no_watermark_raw
> ```
> 
> itu aja yg diganti

itu dmna bang

**Comment by Uzoy** [comment]
*Plugin:* downloader-tiktok.js
*Sender:* 60172736190@s.whatsapp.net
*Chat:* 628112958665-1625393837@g.us
*Command:* .tiktok https://www.tiktok.com/@zaynnketcehh/video/7125074306895203610?_t=8UuLyyPDMIc&_r=1

```TypeError: Cannot read properties of undefined (reading 'includes')
    at tiktokdl (file:///root/wabot/node_modules/@bochilteam/scraper/lib/esm/social-media/tiktok.js:39:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (file:///root/wabot/plugins/downloader-tiktok.js:4:58)
    at async Object.handler (file:///root/wabot/handler.js?id=1660737045504:514:21)```
