### ISSUE TITLE
[MD] ytv/yta error

### ISSUE THREAD

**Issue by Uzoy** [BochilGaming/games-wabot#356]
![Screenshot_2022-06-13-21-55-46-18](https://user-images.githubusercontent.com/78887981/173464495-c2aacfa4-a5a6-4cb7-8413-57a55960257c.jpg)

**Comment by BochilGaming** [comment]
Are ffmpeg has been installed?

**Comment by Uzoy** [comment]
udh

**Comment by Uzoy** [comment]
> Are ffmpeg has been installed?

yes

**Comment by derispewss** [comment]
> ![Screenshot_2022-06-13-21-55-46-18](https://user-images.githubusercontent.com/78887981/173464495-c2aacfa4-a5a6-4cb7-8413-57a55960257c.jpg)

iya itu error kenapa ya ?

**Comment by BochilGaming** [comment]
https://stackoverflow.com/questions/26193654/node-js-catch-enomem-error-thrown-after-spawn?

**Comment by DineshValor** [comment]
Working fine, tested on Termux & Heroku.
