### ISSUE TITLE
[MD] Bug play (EBUSY)

### ISSUE THREAD

**Issue by X3NNN** [BochilGaming/games-wabot#359]
setiap menggunakan fitur play selalu seperti ini
![image](https://user-images.githubusercontent.com/93273094/174515640-a01b6006-d753-413b-bca9-0324acea6f36.png)
![image](https://user-images.githubusercontent.com/93273094/174515740-db8f46a3-32b7-4d7d-ba43-ebb97c866e82.png)

**Comment by BochilGaming** [comment]
saya tidak yakin bahwa error tersebut berasal dari kode games-wabot, yang saya tahu pasti error tersebut hanya terjadi di windows

**Comment by X3NNN** [comment]
> saya tidak yakin bahwa error tersebut berasal dari kode games-wabot, yang saya tahu pasti error tersebut hanya terjadi di windows

iya bang, kalo dijalankan di heroku lancar lancar aja, keknya emang dari pc ku wkwk
