### ISSUE TITLE
[MD] msg del, get error

### ISSUE THREAD

**Issue by Uzoy** [BochilGaming/games-wabot#360]
![Screenshot_2022-06-20-21-12-50-05](https://user-images.githubusercontent.com/78887981/174621362-18084167-b1ea-4b71-ae73-99f391283acf.jpg)

**Comment by BochilGaming** [comment]
Fix?

**Comment by Uzoy** [comment]
![Screenshot_2022-06-21-15-14-05-95](https://user-images.githubusercontent.com/78887981/174750730-e7dd1688-2d1d-47a8-9659-b17538bf8009.jpg)
