### ISSUE TITLE
ini kenapa ya [Heroku]

### ISSUE THREAD

**Issue by X3NNN** [BochilGaming/games-wabot#361]
ini SS dari log di heroku, sempet bisa jalan tiba tiba begitu
![image](https://user-images.githubusercontent.com/93273094/175015506-4769692c-8600-4eeb-91a0-ab601467485e.png)

**Comment by BochilGaming** [comment]
error di "mengirim pesan kembali" . saya belum pernah mengalami error "not-acceptable", jadi saya tidak tahu mengapa. anda mungkin saja bisa 'menghilangkan' masalah tersebut dengan cara me scan kode qr lagi (re scan)

**Comment by X3NNN** [comment]
> error di "mengirim pesan kembali" . saya belum pernah mengalami error "not-acceptable", jadi saya tidak tahu mengapa. anda mungkin saja bisa 'menghilangkan' masalah tersebut dengan cara me scan kode qr lagi (re scan)

untuk session nya yg mana ?

**Comment by X3NNN** [comment]
solved : hapus session rescan qr code
![image](https://user-images.githubusercontent.com/93273094/175089495-a7e93d93-b213-4957-a367-b0a8ef3bd38f.png)
