### ISSUE TITLE
tentang session

### ISSUE THREAD

**Issue by X3NNN** [BochilGaming/games-wabot#362]
kan sekarang ini make session yang berupa file gini
![image](https://user-images.githubusercontent.com/93273094/175293303-b32fdc2b-f568-4bb2-a1ca-3ed15fd84e1b.png)
kalau seandainya make session yang "session.data.json" itu apakah bisa ? soalnya kalo mau di up ke heroku agak susah karena yg session di file itu kadang bisa lebih dari 100 file atau ada solusi buat scan di heroku biar lebih gampang ??

**Comment by BochilGaming** [comment]
tidak
