### ISSUE TITLE
tambahin conn bang

### ISSUE THREAD

**Issue by ghost** [BochilGaming/games-wabot#364]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
conn

**Comment by ghost** [comment]
conn nya tambahin bang

**Comment by BochilGaming** [comment]
Udh ada bwnag, kalau error conn its not defined ubah conn nya ke this atau di handler bisa ditambahi conn seperti
https://github.com/BochilGaming/games-wabot/blob/beaf5085d5caa40c921a25159786b4c641aedd47/plugins/broadcast.js#L4
