### ISSUE TITLE
MD MEMINTA FITUR

### ISSUE THREAD

**Issue by Bintangp02** [BochilGaming/games-wabot#366]
Bang minta Fitur Jika ada orang Yang ngirim link grups langsung masuk ke grups tersebut.

Makasih banyak.

**Comment by BochilGaming** [comment]
kamu bisa menggunakan regex untuk mendeteksi link group tersebut, regex tersebut bisa kamu ambil contoh dari
https://github.com/BochilGaming/games-wabot/blob/beaf5085d5caa40c921a25159786b4c641aedd47/plugins/_antilink.js#L3
dan setelah mendapatkan kode nya, kamu dapat bergabung menggunakan fungsi `conn.groupAcceptInvite` seperti yang dicontohkan pada
https://github.com/BochilGaming/games-wabot/blob/beaf5085d5caa40c921a25159786b4c641aedd47/plugins/join.js#L8
atau 
https://github.com/adiwajshing/Baileys/blob/master/README.md#groups

**Comment by Bintangp02** [comment]
oke trimakasih
