### ISSUE TITLE
[BUG] TIDAK DAPAT MENAMPILKAN QR

### ISSUE THREAD

**Issue by Bintangp02** [BochilGaming/games-wabot#367]
**DI DALAM LOGS**
`{"level":30,"time":1656568639080,"pid":1278,"hostname":"2a06c0a42f81","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"NUfRwwTrJQW6zZufPegfZS1kCTMCcVb9VHJuGRpkUUo="}},"registrationId":203,"msg":"connected to WA Web"}
{"level":30,"time":1656568639144,"pid":1278,"hostname":"2a06c0a42f81","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2204,"tertiary":13},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","regData":{"eRegid":"AAAAyw==","eKeytype":"BQ==","eIdent":"eKWQ6eiFjPKqnaeW2XmYqA3d5A5VA3nqehLIpUDfS1I=","eSkeyId":"AAAB","eSkeyVal":"JEsD3+fApkCVyw37z+G+v6Zysd/KvPo5ZhwDL9m6tUM=","eSkeySig":"pAq9oZ3v0L1WZ4QqdrFuXWzhpXEpy36wf2x1StfuwHHfKDHoAaeTFQQDr3DtCUQDeMq/eokP76OFPogt/o4VAg==","buildHash":"9wB3QMyruh3ylMT/NTeyuQ==","companionProps":"CgdCYWlsZXlzEgYIBBAAGAAYASAA"}},"msg":"not logged in, attempting registration..."}
{"level":50,"time":1656568639323,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568699323,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568719324,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568739328,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568759328,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568779330,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":30,"time":1656568799331,"pid":1278,"hostname":"2a06c0a42f81","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":408,"payload":{"statusCode":408,"error":"Request Time-out","message":"QR refs attempts ended"},"headers":{}}},"trace":"Error: QR refs attempts ended\n    at Timeout.genPairQR [as _onTimeout] (/home/runner/mybotz7/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:375:21)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)","msg":"connection errored"}
{"level":30,"time":1656568799510,"pid":1278,"hostname":"2a06c0a42f81","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"pCnszxG7sUnPZyhwary4V3LlA8lSl+x0Lr6EqFTxdFA="}},"registrationId":203,"msg":"connected to WA Web"}
{"level":30,"time":1656568799661,"pid":1278,"hostname":"2a06c0a42f81","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2204,"tertiary":13},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","regData":{"eRegid":"AAAAyw==","eKeytype":"BQ==","eIdent":"eKWQ6eiFjPKqnaeW2XmYqA3d5A5VA3nqehLIpUDfS1I=","eSkeyId":"AAAB","eSkeyVal":"JEsD3+fApkCVyw37z+G+v6Zysd/KvPo5ZhwDL9m6tUM=","eSkeySig":"pAq9oZ3v0L1WZ4QqdrFuXWzhpXEpy36wf2x1StfuwHHfKDHoAaeTFQQDr3DtCUQDeMq/eokP76OFPogt/o4VAg==","buildHash":"9wB3QMyruh3ylMT/NTeyuQ==","companionProps":"CgdCYWlsZXlzEgYIBBAAGAAYASAA"}},"msg":"not logged in, attempting registration..."}
{"level":50,"time":1656568799937,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568859937,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568879939,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568899941,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
{"level":50,"time":1656568919942,"pid":1278,"hostname":"2a06c0a42f81","msg":"QR code terminal not added as dependency"}
`

**Comment by BochilGaming** [comment]
```sh
npm i qrcode-terminal
```
