### ISSUE TITLE
[REQ] BAGAIMANA CARA SAYA MENGUNAKAN FITUR MONGGODB??

### ISSUE THREAD

**Issue by Bintangp02** [BochilGaming/games-wabot#368]
`mongodb+srv://<username>:<password>@bntgp02.k2q5j.mongodb.net/?retryWrites=true&w=majority`

**Comment by BochilGaming** [comment]
https://github.com/BochilGaming/games-wabot/issues/330#issuecomment-1126630451
Or
#275
