### ISSUE TITLE
ERROR QR SCAN MULTI DEVICE

### ISSUE THREAD

**Issue by Anonymousbot8900** [BochilGaming/games-wabot#370]
![image](https://user-images.githubusercontent.com/107625853/177023795-b1668c0d-03b1-4e03-bcb0-8684e096c44b.png)

**Comment by Anonymousbot8900** [comment]
Cara ngatasinnya gimana ngab?

**Comment by BochilGaming** [comment]
> Cara ngatasinnya gimana ngab?

anda menggunakan script yang tidak support multi-device tetapi anda me-scan menggunakan whatsapp versi multi-device (terbaru) https://github.com/BochilGaming/games-wabot/tree/multi-device#faq. coba gunakan script [ini](https://github.com/BochilGaming/games-wabot/tree/multi-device).
