### ISSUE TITLE
[MD] kadang suka spam hal yg sebelum nya

### ISSUE THREAD

**Issue by Uzoy** [BochilGaming/games-wabot#377]
![Screenshot_2022-07-14-21-21-13-34](https://user-images.githubusercontent.com/78887981/179005547-0ef341dd-14d8-4a21-9621-d2b7e410b2ef.jpg)

Kalo bot dibiarin terlalu lama, nanti suka kirim hal yg sebelum nya gitu.

Oh y kadang kadang gw cek di wa bot gw dan kadang pesan bot ter spam spam gitu tapi pas  keluar masuk chat nya pesan nya ilang(pesan spam nya cuma bisa diliat oleh bot, bukan yg pakai).

**Comment by BochilGaming** [comment]
Maybe related #345. I don't know how to fix it. But I have a solution but it's not a good solution, you can comment [this line](https://github.com/BochilGaming/games-wabot/blob/040c3f52cb92dfb58426943d5497f01be529dd81/lib/connection.js#L27)
