### ISSUE TITLE
Gini lagi

### ISSUE THREAD

**Issue by senotdev** [BochilGaming/games-wabot#383]
internal/process/esm_loader.js:74                         internalBinding('errors').triggerUncaughtException(                                                                                   ^                                                                             Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'                                    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:751:11)                             at Loader.resolve (internal/modules/esm/loader.js:85:40)                                                    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)                                              at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)                                        at link (internal/modules/esm/module_job.js:50:36) {                                                      code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'              }                                                     Exited with code: null

**Comment by BochilGaming** [comment]
Try use node with version >= 16?
