### ISSUE TITLE
[MD] [Log Error] v.replace is not a function

### ISSUE THREAD

**Issue by DineshValor** [BochilGaming/games-wabot#387]
![Screenshot_20220726-152851](https://user-images.githubusercontent.com/98645523/180979813-cf9173cb-6d08-4409-afc5-501ec5743df1.jpg)

Steps to get this error:
1. Add one or more number in 'global.mods' or 'global.prems' in config.js
https://github.com/BochilGaming/games-wabot/blob/1cb3003c072e0c0d569be6d68f84a424ebe298f1/config.js#L11
https://github.com/BochilGaming/games-wabot/blob/1cb3003c072e0c0d569be6d68f84a424ebe298f1/config.js#L12

2. Now Error triggered.
3. Except bot number, no other user able to use bot command and give log error v.replace is not function. It's act like self mode 😓.

**Comment by BochilGaming** [comment]
maybe you fill it with the wrong format?. in the global.mods and global.prems must be an array with string

**Comment by DineshValor** [comment]
> maybe you fill it with the wrong format?. in the global.mods and global.prems must be an array with string

![Screenshot_20220729-152710](https://user-images.githubusercontent.com/98645523/181734996-c0d45a64-5ecd-4884-b03c-4b08d2584bdb.jpg)
Format which i used is shown in attached screenshot.

**Comment by BochilGaming** [comment]
> > maybe you fill it with the wrong format?. in the global.mods and global.prems must be an array with string
> 
> ![Screenshot_20220729-152710](https://user-images.githubusercontent.com/98645523/181734996-c0d45a64-5ecd-4884-b03c-4b08d2584bdb.jpg) Format which i used is shown in attached screenshot.

global.mods = ['numberxxxx',  'number2xxx'] for global.prems same as global.mods

**Comment by DineshValor** [comment]
Okay.
