### ISSUE TITLE
[MD] pesan bot tidak muncul

### ISSUE THREAD

**Issue by Uzoy** [BochilGaming/games-wabot#391]
Kalo saya pake perintah bot, enth knp ga muncul apa apa, pas saya cek di bot saya, ternyata bot ada kirim tapi ga keliatan di wa saya.

Pas saya coba ini dan tanya ke teman teman saya, ada beberapa yg bisa melihat pesan bot dan ada juga yg tidak.

![Screenshot_2022-08-07-13-26-43-01](https://user-images.githubusercontent.com/78887981/183278260-a1fdeb75-5d07-4aac-8796-1d0b085d8e9f.jpg)

![Screenshot_2022-08-07-13-27-09-63](https://user-images.githubusercontent.com/78887981/183278292-b45467c7-9ea2-43d9-8296-2d665be4ebd7.jpg)

**Comment by raseldev18** [comment]
cek issue baileys:v

**Comment by jauhariel** [comment]
> Kalo saya pake perintah bot, enth knp ga muncul apa apa, pas saya cek di bot saya, ternyata bot ada kirim tapi ga keliatan di wa saya.
> 
> Pas saya coba ini dan tanya ke teman teman saya, ada beberapa yg bisa melihat pesan bot dan ada juga yg tidak.
> 
> ![Screenshot_2022-08-07-13-26-43-01](https://user-images.githubusercontent.com/78887981/183278260-a1fdeb75-5d07-4aac-8796-1d0b085d8e9f.jpg)
> 
> ![Screenshot_2022-08-07-13-27-09-63](https://user-images.githubusercontent.com/78887981/183278292-b45467c7-9ea2-43d9-8296-2d665be4ebd7.jpg)

Ini kasusnya buat pesan yg ada buttonnya ga muncul pesannya ke penerima. Gua juga gitu

**Comment by BochilGaming** [comment]
udh di fix di baileys versi github kalau gk salah

**Comment by Uzoy** [comment]
Oh ok.
