### ISSUE TITLE
[MD] unbanchat tidak bisa

### ISSUE THREAD

**Issue by Uzoy** [BochilGaming/games-wabot#413]
![Screenshot_2022-12-17-08-16-09-17](https://user-images.githubusercontent.com/78887981/208215846-7340588d-cd78-4ad7-b609-67c1671d2d68.jpg)

**Comment by Goldn7799** [comment]
Sementara ini harus manual, stop dulu bot nya terus edit di database.json, ubah ban nya jadi false

**Comment by Uzoy** [comment]
Oke terimakasih.
