### ISSUE TITLE
Nonaktifkan fitur

### ISSUE THREAD

**Issue by Dawnfrosty** [BochilGaming/games-wabot#66]
Bikinin dong fitur seperti #disablefitur dan #enablefitur, kadang ada orang yang sering spam fitur di botku:)

**Comment by prioprast** [comment]
Pakai on/off public saja, jadi hanya owner saja yang bisa meeggunakan fiturnya

**Comment by Dawnfrosty** [comment]
buat apa gw request klo gitu, masalahnya botnya memang untuk public bukan untuk pribadi

> Pakai on/off public saja, jadi hanya owner saja yang bisa meeggunakan fiturnya

**Comment by BochilGaming** [comment]
Hapus aja '//' di [sini](https://github.com/BochilGaming/games-wabot/blob/b90fc588fd2ec8d7eb5dedb78b17d66b2225696d/plugins/_antispam.js#L19)

**Comment by Dawnfrosty** [comment]
Ok bang ty
