### ISSUE TITLE
conn.getName tidak berfungsi

### ISSUE THREAD

**Issue by Dawnfrosty** [BochilGaming/games-wabot#72]
conn.getName berubah menjadi [object promise] @ @
![Screenshot_20210817_153845](https://user-images.githubusercontent.com/88573246/129693530-dfbc84b0-0596-4d56-be97-41e0e8339066.jpg)

**Comment by BochilGaming** [comment]
lagi proses fix :)

**Comment by Dawnfrosty** [comment]
Kapan selesai bang?

**Comment by BochilGaming** [comment]
> Kapan selesai bang?

udh selesai dari kemaren-kemaren, tapi blm up ke github
